### ISSUE TITLE
how to remove peer

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#102]
When a peer/store is down, pd should do auto-balance to guarantee the raft group has correct replicas.

1. TiKV store reports information to Pd regularly, if pd doesn't receive the message from a store for a long time and pd also can't send command to it, pd can think the store is down, and can notify users for it. (Notice that pd doesn't do auto-balance directly here.)
2. The leader in a raft group detects that it can't communicate with a follower for a long time, so it tells pd about it, pd guarantees that the peer or the whole store contains this peer is down, it can send ConfChange remove command to the leader, then the leader remove the dead peer. Later, the leader peer can ask ConfChange add command to pd again if it finds the replica number is less. 
3. The dead peer may be isolated, so it can't receive the ConfChange remove log, and can't remove itself, if the peer finds it can't receive any message from other peers for a long time, it asks the pd whether it is still in the region, if not, remove itself directly.

/cc @ngaut @qiuyesuifeng @tiancaiamao

**Comment by qiuyesuifeng** [comment]
In phase 2,  if the leader in a raft group detects that it can't communicate with a follower for a long time, but pd finds that it can communicate with the store which the follower in, so what will happen?

**Comment by siddontang** [comment]
wait the peer re-add the raft group, nothing to do, maybe.
and tell the user about network partition happens.

**Comment by tiancaiamao** [comment]
LGTM
