### ISSUE TITLE
Support unescape hex like keys

### ISSUE THREAD

**Issue by breeswish** [pingcap/pd#1040]
pd-ctl produce keys in hex format, like `t\x80\x00\x00\x00\x00\x00\x00\xff\xdc_r\x80\x00\x00\x006\xff\x95\xb7\x86\x00\x00\x00\x00\x00\xfa`. We cannot unescape this format for now, which is inconvenient to be used in tikv-ctl.

**Comment by siddontang** [comment]
PTAL @nolouch

**Comment by breeswish** [comment]
Oops, this issue is opened in wrong project! I'm going to move it to tikv. Closing.
