### ISSUE TITLE
simulator coredump on balance_leader case!!!

### ISSUE THREAD

**Issue by eric2016fly** [pingcap/pd#1086]
os version: CentOS Linux release 7.4.1708 (Core
go version: go1.10.1 linux/amd64
simulator version: release-2.0

I built simulator by simply type “go build” under $HOME/src/github.com/pingcap/pd/cmd/simulator
 and run it by 
`./simulator --conf="balance-leader" --serverLog="info" --simLog="info"`
 And it got coredump , I've attached the whole log:
[sim.log](https://github.com/pingcap/pd/files/2031016/sim.log)

Below is the backtrace of gdb which might help debugging:

![image](https://user-images.githubusercontent.com/18022717/40425273-800605a2-5eca-11e8-8fe4-9fa8fcb4b780.png)

**Comment by disksing** [comment]
Thanks for your report. PTAL @nolouch

**Comment by left2right** [comment]
why not  checking region is nil before calling RemoveRegion in AddRegion?
```
func (r *RegionsInfo) AddRegion(region *RegionInfo) []*metapb.Region {
	// Add to tree and regions.
	overlaps := r.tree.update(region.Region)
	// check region is nil before remove
        for _, item := range overlaps {
                  rg := r.GetRegion(item.Id)
                  if rg == nil {
                            ......
                  } else {
                           r.RemoveRegion(rg)
                }	
	}
.......
}


```

**Comment by eric2016fly** [comment]
![default](https://user-images.githubusercontent.com/18022717/40479759-0886878a-5f7f-11e8-8c83-22fd3476ae13.png)

Should the logic be enhanced in AddRegion function?  Before removing region, rg should be checked to see if it is nil.

**Comment by disksing** [comment]
@Connor1996 Please take a look.

**Comment by eric2016fly** [comment]
@disksing Thanks for your quick reply.

**Comment by nolouch** [comment]
@eric2016fly  yep, we enable the `learner` in default. the simulator incompatible with it now.  you can help us fix it if you are interested and have time.

**Comment by nolouch** [comment]
fixed via https://github.com/pingcap/pd/pull/1151
