### ISSUE TITLE
when pd lost  (N-1)/2 members how to recover pd?

### ISSUE THREAD

**Issue by ccdeville** [pingcap/pd#1109]
I have a pd cluster with three members ，because of some failures, two members lost。Surviving member have all snapshot  ，how to recover the pd cluster

**Comment by nolouch** [comment]
@ccdeville  we have a another way to recover the PD cluster via `pd-recover` with following steps:
- get `cluster-id`, you can find in PD log or TiKV log
- get `max-alloce-id`, you can grep "allocates" in PD logs, find the maximum id. or directlly given a enough lager number like 100000000.  
- shut down the cluster, and start a new PD cluster
- run `pd-recover`: pd-recover --cluster-id=\<cluster-id\> --alloc-id=\<max-store-id\> --endpoints=http://\<one-new-pd-ip\>:2379
- restart the new pd cluster. **Note**: the TiKV and TiDB should specify correct pd address.

**Comment by ccdeville** [comment]
@nolouch Thank you very much for your answer，I have recovered pd cluster as you provided,but
our tikv cluster also lost two members ,now,how to recover tikv?

**Comment by nolouch** [comment]
you can delete the two store with `pd-ctl`. but there is a problem, if you replicas number is 3, that may exist some region already lost quorum peers, it cannot elect a new leader. you can [force the region to recover via `tikv-ctl`](https://github.com/pingcap/docs/blob/master/tools/tikv-control.md#force-region-to-recover-the-service-from-multiple-replicas-failure),but this is unsafe, may be lost some data.

**Comment by ccdeville** [comment]
Thanks again for your answer, I have restored my TIDB cluster, the last question,if I have two datacenters, datacenter 1 has two KV members, datacenter 2 has three KV members, I use the label parameter to ensure all regions Leader in datacenter 1, when datacenter 2 be destroyed,  I think there will be no data loss even if I use unsafe-recover ,is that true？

**Comment by disksing** [comment]
@ccdeville 
It is true that the region leader is always up to date.
However, with the label property config, pd-server only transfers leaders out of datacenter 2 -- it doesn't prevent leaders from drifting to datacenter. That is to say, there is still a small probability that some leaders appear in datacenter2 in a short period of time and write some data.

**Comment by ccdeville** [comment]
@disksing 
Thanks,
When there are two datacenters, there is always a chance of losing data，Can I comprehend the meaning in this way？

**Comment by disksing** [comment]
That's right. With the label property config, the probability of losing data is low, but that is still possible.

**Comment by truong-hua** [comment]
@nolouch regarding this case, @ccdeville told that he has all snapshot. So why don't we support to recover from existed snapshot (like etcd --force-new-cluster) but we have to recover from nothing? People should keep PD data persistent on disk too, and is it a good place to recover than /pd-recover?

**Comment by disksing** [comment]
I think one of the benefits of having the user set these parameters manually is that it makes the user understand the risks associated with it.
