### ISSUE TITLE
close pd client meet `context canceled` error

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/pd#1134]
In tidb-binlog, we will connect to pd to get some information, it always get `context canceled` error when close pd client, the logs are below:

```
time="2018-07-03T13:24:37+08:00" level=info msg="[pd] create pd client with endpoints [http://127.0.0.1:2379]"
time="2018-07-03T13:24:37+08:00" level=info msg="[pd] leader switches to: http://192.168.31.246:2379, previous: "
time="2018-07-03T13:24:37+08:00" level=info msg="[pd] init cluster id 6572000418809746278"
2018/07/03 13:24:37 server.go:81: [info] clusterID of drainer server is 6572000418809746278
time="2018-07-03T13:24:37+08:00" level=error msg="[pd] create tso stream error: rpc error: code = Canceled desc = context canceled"
```

This error dosen't matter, but may make some confused to users, can we refine the code to avoid this error?

the pd version I use:
version: eed819b6999186a4bf2d25255f8d61b371a450d6

**Comment by disksing** [comment]
Hi @WangXiangUSTC , do you close the pd client right after done use of it?

**Comment by WangXiangUSTC** [comment]
the code like this:
```
	pdCli, err := getPdClient(cfg)
	if err != nil {
		return nil, errors.Trace(err)
	}

	clusterID = pdCli.GetClusterID(ctx)
	pdCli.Close()
```
@disksing

**Comment by disksing** [comment]
hi @WangXiangUSTC , I have sent a PR to fix it. If it is convenient, you can try it with the branch of PR in advance.

**Comment by WangXiangUSTC** [comment]
@disksing Thanks!
