### ISSUE TITLE
服务器断电，tidb server 没法连接

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/pd#1145]
有这么个情况：
tidb server ,pd  共用3台服务器,各3个节点
tikv  3台服务器,各3个节点     
和官方上的类似
发现   tidb server ,pd服务器，    利用ansible 直接停掉一个服务节点。还是能正常连接4000 端口。
但是  tidb server ,pd服务器 其中一台断电后，另外两台的4000 端口一直连不上(报错 pd server timeout 9001)。

**Comment by siddontang** [comment]
what is the log in other two PDs?

**Comment by shenlijungg** [comment]
pd server timeout 9001

**Comment by shenlijungg** [comment]
etcd_kv.go:117: [error] load from etcd error: context deadline exceeded

**Comment by disksing** [comment]
Hi @shenlijungg , could you upload log files of pd-servers?

**Comment by shenlijungg** [comment]
能提供邮件吗，我直接@你邮件！日志里有服务器信息不太安全。

**Comment by disksing** [comment]
@shenlijungg Please send to i@disksing.com, thanks!

**Comment by shenlijungg** [comment]
@disksing   能看到问题吗

**Comment by disksing** [comment]
Sorry but I haven't received your mail yet. Have you sent a mail>

**Comment by siddontang** [comment]
@shenlijungg 

do you restart your TiDB servers, can restarting solve this problem?

**Comment by shenlijungg** [comment]
@siddontang  需要将断电的TIDB服务 重新启动后，其他的tidb节点才能正常访问，感觉是leader一直在断电的那台 。

**Comment by siddontang** [comment]
oh, interesting, please give us the PD logs. seems that @disksing has not received your logs yet, you can send me again, tl@pingcap.com 

Btw, can you reproduce it every time?

**Comment by shenlijungg** [comment]
@disksing  你们的邮箱发不了大附件  ，关闭问题吧，后面问题复现我在提问题，感谢

**Comment by siddontang** [comment]
@shenlijungg 

how large is the log? can you compress it? maybe you can try sending to siddontang@gmail.com :-)

**Comment by disksing** [comment]
Maybe you can split log files and only send the part from when you use ansible stop node, to when the query fails with "PD server timeout" error.

**Comment by disksing** [comment]
Close it due to no feedback for a long time. Please feel free to reopen it if need.
