### ISSUE TITLE
some specific  network failure leads to  Abnormal problem

### ISSUE THREAD

**Issue by wilanhuang** [pingcap/pd#1161]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I simulated a network failure on pd leader machine,and I found that TiDB Cluster can not work very well in this situation which may be rarely happened; 
I run cmds on PD leader machine :
iptables -A INPUT    -p tcp --dport 2379  -j DROP 
iptables -A OUTPUT   -p tcp --dport 2379  -j DROP

2. What did you expect to see?

 PD cluter elect a new PD leader 

3. What did you see instead?
a、any Query got timeout：(ERROR 9001 (HY000): PD server timeout[try again later])
b、the PD followers print error log continuously：2018/07/25 14:24:05.596 leader.go:103: [info] pd3 is not etcd leader, skip campaign leader and check later

4. What version of PD are you using (`pd-server -V`)?
Release Version: v2.0.3

**Comment by nolouch** [comment]
Hi, @wilanhuang  Etcd elect new leader will spend some time, could you show the detail logs about the election.

**Comment by disksing** [comment]
Closing it due to no response for a long time.
