### ISSUE TITLE
Add more 3 tikv nodes，but the memory usage still not balance?

### ISSUE THREAD

**Issue by denghuancong** [pingcap/pd#1226]
base info
- tidb version: v2.0.4
------------------------------------

first , we use 3 nodes of tikv to store data, and we bench to test the memory usage. We found that the memory usage in one nodes is very high , other is lower . 
so, we add 3 more tikv node to the cluster ,  and we found that the hot node still the origin one and laster oom by the system . 
why we add 3 more nodes,  the memory usage still not balance ? or still not change to other ?

here is the store info from pd-ctl, 6 nodes is the same leader/region weight 
```
"leader_weight": 1,
"region_weight": 1,
```

**Comment by disksing** [comment]
Hi @denghuancong , the balance of PD does not include scheduling for TiKV memory. In fact, the memory usage of TiKV is managed by itself, mainly affected by the configuration and query workload, and has nothing to do with the amount of data.

**Comment by denghuancong** [comment]
@disksing  Is there some way or cmd to let memory usage more balance?

**Comment by hicqu** [comment]
Thanks for your report. Could you describe your situation with more details? We need such informations at least:

The memory usage of that node is growing up when you bench TiKV?
You use sysbench or other similar things? Bench for read or write?

**Comment by denghuancong** [comment]
docker stats show ：
```
d836540b1874        kv01   20.28%              3.474GiB / 4GiB       86.84%              3.37GB / 6.26GB     36.2GB / 35.8GB     103
（just oom and restart）e1bfd1d311fd        kv02   104.46%             569.4MiB / 4GiB       13.90%              206MB / 181MB       1.17GB / 233MB      100
1f6e4a66b5bf        kv03   43.00%              3.13GiB / 4GiB        78.25%              3.01GB / 3.25GB     32.6GB / 40.6GB     98
29e2ff28c3d0        kv04   44.34%              3.5GiB / 4GiB         87.49%              12.3GB / 7.03GB     20.5GB / 25.7GB     103
4b8a8d590512        kv05   103.07%             2.931GiB / 4GiB       73.27%              9.55GB / 5.41GB     7.76GB / 11.8GB     103
f6d9b722e934        kv06   69.30%              3.164GiB / 4GiB       79.11%              9.7GB / 6.53GB      11.5GB / 17.6GB     103
````
we use sysbench to run , both read and write.

**Comment by denghuancong** [comment]
@hicqu 
1.CONTAINER ID        
2.NAME                                  
3. CPU %               
4.MEM USAGE / LIMIT     
5.MEM %               
6.NET I/O             
7.BLOCK I/O          
8. PIDS

**Comment by BusyJay** [comment]
What's the deployment topology?

**Comment by disksing** [comment]
@BusyJay Do you want more information?

**Comment by BusyJay** [comment]
A large amount of memory used in TiKV are rocksdb cache. Can you compare whether they are the same on all the nodes? Are the rest balanced after subtracting cache memory size?

**Comment by disksing** [comment]
Closing it for inactivity. Please feel free to reopen the issue if need.
