### ISSUE TITLE
make schedule interval params configurable

### ISSUE THREAD

**Issue by lerencao** [pingcap/pd#1247]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Schedulers have three schedule interval params, which are `min_interval`, `max_interval`, `interval_growth_type`.

However, It's not possible to adjust these parameters dynamically.

One possible solution is adding more fileds in 

``` go
// SchedulerConfig is customized scheduler configuration
type SchedulerConfig struct {
	Type    string   `toml:"type" json:"type"`
	Args    []string `toml:"args,omitempty" json:"args"`
	Disable bool     `toml:"disable" json:"disable"`
        ScheduleInterval SchedulerIntervalConfig `json:"schedule_interval"`
}
type ScheduleIntervalConfig struct {
       MinInterval time.Duration
       MaxInterval time.Duration
       IntervalGrowthType intervalGrowthType
}
``` 

If this feature is wanted, I will try to give a PR to address it.

2. What did you expect to see?

3. What did you see instead?

4. What version of PD are you using (`pd-server -V`)?

**Comment by nolouch** [comment]
@lerencao  Is the default policy not meeting your needs yet? I would rather minimize the configuration.

**Comment by lerencao** [comment]
@nolouch Yes. The default settings(10ms for min_interval) is too fast for our cluster. and almost every scheduler uses this config except balance-adjacent-region.

**Comment by nolouch** [comment]
@lerencao  The coordinator will auto-tune the speed, and also we have the limiter. maybe you can decrease the limit of balance-adjacent-region.

**Comment by rleungx** [comment]
Since this issue has not been updated for a long time, close it. Feel free to reopen it if you have other questions.
