### ISSUE TITLE
how to add balance-leader-scheduler and balance-region-scheduler again

### ISSUE THREAD

**Issue by Hanyu2015** [pingcap/pd#1286]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
use pd-ctl
scheduler remove balance-leader-scheduler and scheduler remove balance-region-scheduler

2. What did you expect to see?
add balance-leader-scheduler and balance-region-scheduler again

3. What did you see instead?
scheduler show 
["balance-hot-region-scheduler",
"label-scheduler"]

4. What version of PD are you using (`pd-server -V`)?
v2.1.0-rc.2

**Comment by rleungx** [comment]
@Hanyu2015 Thanks for your feedback. For now, you can use the below commands to add them back:
```
curl -X POST -H "Content-Type: application/json" --data '{"name":"balance-leader-scheduler"}' http://${IP}:${PORT}/pd/api/v1/schedulers
curl -X POST -H "Content-Type: application/json" --data '{"name":"balance-region-scheduler"}' http://${IP}:${PORT}/pd/api/v1/schedulers
```
We will support it in `pd-ctl` ASAP.
