### ISSUE TITLE
What is replica checker metric in PD Grafana dashboard

### ISSUE THREAD

**Issue by Guru107** [pingcap/pd#1295]
Replica Checker metric shows `not_better` . Does this mean replicas are not available?

<img width="420" alt="screen shot 2018-10-24 at 12 17 07 pm" src="https://user-images.githubusercontent.com/5235591/47411741-5d428f00-d787-11e8-91ab-5cc8dc5c6181.png">

1. What did you do?
If possible, provide a recipe for reproducing the error.
NA

2. What did you expect to see?
NA

3. What did you see instead?

NA
4. What version of PD are you using (`pd-server -V`)?
pd-server v2.0.3

**Comment by rleungx** [comment]
@Guru107 `not_better` here means we can not find a new store which is better than the old one. In this case, we won't make replica replacement for the region on the old store.

**Comment by Guru107** [comment]
@rleungx  Is it something to be worried about?

**Comment by rleungx** [comment]
@Guru107 Maybe you can take a look at `Region Health` for more details. If there is nothing strange in `Region Health`. It is ok for this metrics.

**Comment by Guru107** [comment]
@rleungx Where can I find `Region Health` metric on PD Grafana Page? There isn't any graph with that name

**Comment by rleungx** [comment]
@Guru107 You can find it from a `Row` named `Cluster`

**Comment by Guru107** [comment]
Thank you 👍
