### ISSUE TITLE
hot-region-scheduler may disappear in grafana

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/pd#1341]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Add `shuffle-leader-scheduler` at 9:50am and remove it at 10:05am.

2. What did you expect to see?
`hot-region-scheduer` should exist in grafana.

3. What did you see instead?
`hot-region-scheduer` disappeared between 9:57am to 9:59am.
<img width="1266" alt="screen shot 2018-11-23 at 10 07 07 am" src="https://user-images.githubusercontent.com/19700528/48926304-ac571d80-ef07-11e8-98da-6bd0a7a4d362.png">

4. What version of PD are you using (`pd-server -V`)?
Release Version: v2.1.0-rc.2-57-g0f89ea6-dirty
Git Commit Hash: 0f89ea6df0178fe764d1755757fc50c2cf2c07b3
Git Branch: HEAD
UTC Build Time:  2018-11-23 01:24:42

**Comment by rleungx** [comment]
@zhangjinpeng1987 It seems that the `hot-region-scheduer` wasn't allowed to schedule the region at that time. This is because some kinds of operator reaching their limit.
