### ISSUE TITLE
May be we can optimize this function?

### ISSUE THREAD

**Issue by yangwenmai** [pingcap/pd#1359]
1. Whether can be optimized？

May be we can optimize this logic.

https://github.com/pingcap/pd/blob/master/server/schedulers/hot_region.go#L374
```golang
func (h *balanceHotRegionsScheduler) selectDestStore(candidateStoreIDs []uint64, regionFlowBytes uint64, srcStoreID uint64, storesStat core.StoreHotRegionsStat) (destStoreID uint64) {
	sr := storesStat[srcStoreID]
	srcFlowBytes := sr.TotalFlowBytes
	srcHotRegionsCount := sr.RegionsStat.Len()

	var (
		minFlowBytes    uint64 = math.MaxUint64
		minRegionsCount        = int(math.MaxInt32)
	)
	for _, storeID := range candidateStoreIDs {
		if s, ok := storesStat[storeID]; ok {
			if srcHotRegionsCount-s.RegionsStat.Len() > 1 && minRegionsCount > s.RegionsStat.Len() {
				destStoreID = storeID
				minFlowBytes = s.TotalFlowBytes
				minRegionsCount = s.RegionsStat.Len()
				continue
			}
			if minRegionsCount == s.RegionsStat.Len() && minFlowBytes > s.TotalFlowBytes &&
				uint64(float64(srcFlowBytes)*hotRegionScheduleFactor) > s.TotalFlowBytes+2*regionFlowBytes {
				minFlowBytes = s.TotalFlowBytes
				destStoreID = storeID
			}
		} else {
			destStoreID = storeID
			return
		}
	}
	return
}
```

When looping through candidateStoreIDs, if there are multiple matches, then the last one will always overwrite the data that has been stored in destStoreID. Finally, the destStoreID we get may not be optimal.

2. What version of PD are you using (`pd-server -V`)?

```sh
Release Version: v2.1.0-rc.2-64-g8e2ec1e
Git Commit Hash: 8e2ec1e832198ea81c8b03717037f4eb2261affc
Git Branch: master
UTC Build Time:  2018-12-04 09:30:07
```

**Comment by disksing** [comment]
PTAL @nolouch

**Comment by nolouch** [comment]
@yangwenmai  Yes, you are right. `storesStat` can be updated after the operator finished. so we use the limiter mechanism to ensure the scheduler not produce multiple operators base the same `storesStat`. maybe you can help up do more better.

**Comment by rleungx** [comment]
Since we have already implemented a new scheduling policy, the function mentioned above no longer exists. Close it.
