### ISSUE TITLE
make error "checksum mismatch"

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/pd#1408]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
make

2. What did you expect to see?

3. What did you see instead?
CGO_ENABLED=0 go build -ldflags '-X "github.com/pingcap/pd/server.PDReleaseVersion=v3.0.0-alpha-79-g38221ce" -X "github.com/pingcap/pd/server.PDBuildTS=2019-01-05 09:33:35" -X "github.com/pingcap/pd/server.PDGitHash=38221cebaf157aef1f68e3839bd91cdd73ed0cdf" -X "github.com/pingcap/pd/server.PDGitBranch=master"' -o bin/pd-server cmd/pd-server/main.go
go: verifying github.com/coreos/etcd@v0.0.0-20180530235116-2b3aa7e1d49d: checksum mismatch
	downloaded: h1:X15ii/EYFV9j7Hgj8VwtpSe65vGy7RYrX9oIDgXvRHk=
	go.sum:     h1:zhOJad+Mv6DJ3IdTSoOubih2OeMTZFH+qs21GS5uHP8=
make: *** [build] Error 1

4. What version of PD are you using (`pd-server -V`)?
commit 38221cebaf157aef1f68e3839bd91cdd73ed0cdf

**Comment by rleungx** [comment]
@fredchenbj Thanks for your feedback!
And what is your go version?

**Comment by fredchenbj** [comment]
@rleungx go version go1.11.4 darwin/amd64

**Comment by rleungx** [comment]
@fredchenbj Can you try to run `go clean -modcache` first?
There is a known issue for this problem. See https://github.com/golang/go/issues/29281.

**Comment by fredchenbj** [comment]
@rleungx after run `go clean -modcache`, it print 

> can't load package: package github.com/pingcap/pd: unknown import path "github.com/pingcap/pd": cannot find module providing package github.com/pingcap/pd

, and then run `make`, the above error still occurs.

**Comment by fredchenbj** [comment]
@rleungx after I run `go clean -modcache`, the above error still occurs.

**Comment by rleungx** [comment]
@fredchenbj Can you remove `go.sum` and regenerate it to see if it can success? Or use `go 1.11.2` instead.

**Comment by fredchenbj** [comment]
@rleungx I change go.sum with downloaded checksum, it is ok now.

> 	downloaded: h1:X15ii/EYFV9j7Hgj8VwtpSe65vGy7RYrX9oIDgXvRHk=
	go.sum:     h1:zhOJad+Mv6DJ3IdTSoOubih2OeMTZFH+qs21GS5uHP8=

**Comment by rleungx** [comment]
Feel free to ask any question if you have.
