### ISSUE TITLE
discussion: remove namespace?

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#1416]
We have built a namespace feature to balance table, but we never used this and can't guarantee this can work well or not. Meanwhile, this feature introduces complexity and hard to maintain, so maybe it is better to remove this.

By the way, this year, we may provide another way that balancing by key-range, this is similar to namespace but more simple. And we also can let the user balance the regions in the specified key-range to some places explicitly. 

/cc @huachaohuang @disksing

**Comment by ngaut** [comment]
Yes, we should remove namespace, due to the complexity,  it is too complicate to manage lots of namespace.
