### ISSUE TITLE
cache.TTL goroutine leak

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#1428]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
pprof goroutine on a running PD

2. What did you expect to see?

3. What did you see instead?
There are 291 TTL doGC() goroutines:
```
291 @ 0x42df9b 0x42e043 0x405ade 0x4057cb 0x9c9813 0x45c041
#	0x9c9812	github.com/pingcap/pd/server/cache.(*TTL).doGC+0x292	/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/cache/ttl.go:113
```

4. What version of PD are you using (`pd-server -V`)?
master

-----
Explanation:

For each TTL cache, a background goruntine is created: https://github.com/pingcap/pd/blob/b93cac8d557a71cf8962912230bdd38a9dbbd312/server/cache/ttl.go#L38-L47
There is no way to stop the goroutine after the TTL cache is dropped.

The `BalanceRegionScheduler` and `BalanceLeaderScheduler` contains a TTL cache:
https://github.com/pingcap/pd/blob/b93cac8d557a71cf8962912230bdd38a9dbbd312/server/schedulers/balance_region.go#L46

The `BalanceRegionScheduler` and `BalanceLeaderScheduler` can be removed and created danamically. They can also be created temporarily by other scheduler:
https://github.com/pingcap/pd/blob/b93cac8d557a71cf8962912230bdd38a9dbbd312/server/schedulers/scatter_range.go#L52-L62

That will cause the goroutine leak.

-----
Possible fix:
Use context to cancel the goroutine when the TTL is dropped.

/cc @ngaut

**Comment by lhy1024** [comment]
It seems to be solved by #1758 @rleungx
