### ISSUE TITLE
Increase max-replicas on large cluster causes jittering

### ISSUE THREAD

**Issue by sunxiaoguang** [pingcap/pd#1435]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
On a cluster with large number of regions and heavy writing load, increase max-replicas with pd-ctl caused write throughput jittering.

2. What did you expect to see?
Missing peers are fixed with less impaction to online write 

3. What did you see instead?
Write was stalled for couple of minutes

4. What version of PD are you using (`pd-server -V`)?
Release Version: v2.1.3
Git Commit Hash: e4124210b3cb423997e71c19f1830567f39329aa
Git Branch: release-2.1
UTC Build Time:  2019-01-28 06:47:26

**Comment by sunxiaoguang** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/3982329/53018368-25c1c600-348d-11e9-80fe-f500e6ee9d72.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3982329/53018421-44c05800-348d-11e9-87e6-809ee4e9b649.png">

**Comment by sunxiaoguang** [comment]
Update: the total number of regions is close to fifty thousands, therefore pd already tried to throttle the background tasks.

**Comment by nolouch** [comment]
@sunxiaoguang  Could you show more metrics about `raft-io`  and ` scheduler-prewrite / commit` in the TiKV board?

**Comment by sunxiaoguang** [comment]
> @sunxiaoguang Could you show more metrics about `raft-io` and ` scheduler-prewrite / commit` in the TiKV board?

Sorry for the late reply. The historical metrics were unfortunately deleted. However I suspect the jittering was caused by faulty hardware. After removed the three suspicious nodes, the whole system works like a charm. So I'm gonna close this issue. Thank you.
