### ISSUE TITLE
some questions about pd node expansion

### ISSUE THREAD

**Issue by XSHui** [pingcap/pd#1445]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
We have 3 pd nodes deployed by docker, now we want to expension pd node.

New `start.sh` as below
```
--name=pd4 \
                --client-urls="http://host4:2379" \
                --peer-urls="http://host4:2380" \
                --join="http://host1:2379"
```

2. My question
- Do I need to modify --join in `start.sh` to --initial-cluster ( the same `start.sh` as the first time create pd cluster)， to prevent filad when we recreate or restart the new node while the `--join`node in start.sh was deleted ?

- Do I need to change `tart.sh` of original pd nodes add new node info after --initial-cluster,  to prevent recreate or restart faild next time  (the pd node may be migrated a lot of times)?

3. What version of PD are you using (`pd-server -V`)?
pd:v2.0.4

**Comment by XSHui** [comment]
I had done some experiment to test,  it seems like that I have no need to modify any `start.sh` after new expansion started. I think the heartbeat mechanism make it possible,  ,right ？

**Comment by disksing** [comment]
@XSHui Sorry for the late reply. You are correct. The 2 parameters are only read when PD starts at the first time (with no persist data).
