### ISSUE TITLE
pd build error，etcd linked problem

### ISSUE THREAD

**Issue by denghuancong** [pingcap/pd#1447]
I pull the lastest code of pd server，it build error。I dig some info that because the etcd path has changed， so the pd project should change the path？or how can I fix to build the pd server？

the code branch at 
```
* (detached from v2.1.3)
  master
```
etcd error
```
../github.com/coreos/etcd/clientv3/auth.go:116:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable

```

**Comment by rleungx** [comment]
I'm not sure what do you want to do. If you only want to get master branch or v2.1.3 compiled, you can `git checkout -f master/v2.1.3`.

**Comment by denghuancong** [comment]
I fixed by myself， you can close @rleungx
