### ISSUE TITLE
etcd issue in commit b93cac8

### ISSUE THREAD

**Issue by aribeth97** [pingcap/pd#1450]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

The commit b93cac8d557a71cf8962912230bdd38a9dbbd312 introduce an etcd problem.

Create a pd cluster by starting 3 pd servers. Then use pd-ctl to delete one from cluster:
`./bin/pd-ctl -d member delete name pd1`

After that observe log output of pd1:
```
WARNING: 2019/03/04 21:11:23 Failed to dial localhost:23790: grpc: the connection is closing; please retry.
WARNING: 2019/03/04 21:11:26 Failed to dial localhost:23790: grpc: the connection is closing; please retry.
WARNING: 2019/03/04 21:11:29 grpc: addrConn.createTransport failed to connect to {localhost:23790 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:23790: socket: too many open files". Reconnecting...
WARNING: 2019/03/04 21:11:30 grpc: addrConn.createTransport failed to connect to {localhost:23790 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:23790: socket: too many open files". Reconnecting...
2019/03/04 21:11:30.963 etcd_kv.go:116: [error] load from etcd error: context deadline exceeded
2019/03/04 21:11:30.964 etcd_kv.go:119: [warning] kv gets too slow: key /pd/6664723512884688702/leader cost 10.000432608s err context deadline exceeded
2019/03/04 21:11:30.964 leader.go:87: [error] get leader err context deadline exceeded
WARNING: 2019/03/04 21:11:30 Failed to dial localhost:23790: context canceled; please retry.
```

Meanwhile there are a lot of sockets created by pd server.

2. What did you expect to see?
Before this commit, pd can handle this situation gracefully:

```
2019/03/04 21:05:45.034 leader.go:87: [error] get leader err etcdserver: server stopped
2019/03/04 21:05:47.810 etcd_kv.go:116: [error] load from etcd error: etcdserver: server stopped
2019/03/04 21:05:47.810 etcd_kv.go:119: [warning] kv gets too slow: key /pd/6664722048153862388/leader cost 2.575597922s err etcdserver: server stopped

```

3. What did you see instead?
described in question 1.

4. What version of PD are you using (`pd-server -V`)?
Release Version: v3.0.0-beta-5-gb93cac8
Git Commit Hash: b93cac8d557a71cf8962912230bdd38a9dbbd312
Git Branch: HEAD
UTC Build Time:  2019-03-05 02:10:12

**Comment by rleungx** [comment]
@aribeth97 Thanks for your feedback!
The reason why we revert this commit is we met another bug in etcd. Could you `ulimit -n` to see the number of the max open files of your system?

**Comment by aribeth97** [comment]
> @aribeth97 Thanks for your feedback!
> The reason why we revert this commit is we met another bug in etcd. Could you `ulimit -n` to see the number of the max open files of your system?

[root@Dell-PowerEdge ~]# ulimit -n
1024

I understood the ETCD package will be updated. Hopefully we can verify and ensure this issue will be solved at that time.

**Comment by rleungx** [comment]
I think you can change the limit of max open files in your system. As for the bug of etcd, we have already raised a PR to fix it.

**Comment by rleungx** [comment]
This issue is outdated, I will close it. If you have any questions, feel free to reopen it.
