### ISSUE TITLE
The `make` command didn't pass.

### ISSUE THREAD

**Issue by elitecodegroovy** [pingcap/pd#1455]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
The go module defines the package version is not always OK. 
For example, the following is go module definition. "	
golang.org/x/crypto v0.0.0-20180503215945-1f94bef427e3 // indirect
golang.org/x/time v0.0.0-20180412165947-fbb02b2291d2 // indirect
"
It failed to fetch the dependencies when I run `make` command, the message show it this package version has been removed.

e.g.: 
go: gopkg.in/airbrake/gobrake.v2@v2.0.9: unrecognized import path "gopkg.in/airbrake/gobrake.v2" (https fetch: Get https://gopkg.in/airbrake/gobrake.v2?go-get=1: proxyconnect tcp: EOF)

 

2. What did you expect to see?
The `make` command passed.

3. What did you see instead?
The correct package versions are defined.

4. What version of PD are you using (`pd-server -V`)?
Master.

**Comment by elitecodegroovy** [comment]
The package version `go.uber.org/zap@v1.9.1` has been removed, look the following error info: 
“
go.uber.org/zap@v1.9.1: unrecognized import path "go.uber.org/zap" (https fetch: Get https://go.uber.org/zap?go-get=1: proxyconnect tcp: EOF)
”

**Comment by elitecodegroovy** [comment]
Today I built the Tidb project, the same issue occurred .
`
go: golang.org/x/time@v0.0.0-20181108054448-85acf8d2951c: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: proxyconnect tcp: EOF)
`

**Comment by gregwebs** [comment]
What go version are you using? go < 1.11.5 has incorrect checksums. You need to upgraded to go >= 1.11.5 and run `GO111MODULE=on go clean -modcache`.

**Comment by elitecodegroovy** [comment]
The issue can be closed. I found the issue is caused by the proxy software.

**Comment by elitecodegroovy** [comment]
> What go version are you using? go < 1.11.5 has incorrect checksums. You need to upgraded to go >= 1.11.5 and run `GO111MODULE=on go clean -modcache`.

Thank you!
