### ISSUE TITLE
unsafe goroutine check

### ISSUE THREAD

**Issue by bradyjoestar** [pingcap/pd#1460]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?If possible, provide a recipe for reproducing the error.
code bug report

I am reading the `operator.go` and find the following code:
https://github.com/pingcap/pd/blob/59968e186cf23bdc172cd7be3c3c7e22aeb600f0/server/schedule/operator.go#L330
```
// Check checks if current step is finished, returns next step to take action.
// It's safe to be called by multiple goroutine concurrently.
func (o *Operator) Check(region *core.RegionInfo) OperatorStep {
	for step := atomic.LoadInt32(&o.currentStep); int(step) < len(o.steps); step++ {
		if o.steps[int(step)].IsFinish(region) {
			operatorStepDuration.WithLabelValues(reflect.TypeOf(o.steps[int(step)]).Name()).
				Observe(time.Since(time.Unix(0, atomic.LoadInt64(&o.stepTime))).Seconds())
			atomic.StoreInt32(&o.currentStep, step+1)
			atomic.StoreInt64(&o.stepTime, time.Now().UnixNano())
		} else {
			return o.steps[int(step)]
		}
	}
	return nil
}
```

I don't know when to called by multiple goroutine but maybe it isnt safe?

For test, I write the following code:
```
{
		var count int32 =  0
		wg := sync.WaitGroup{}
		for i := 0; i < 100; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				value := atomic.LoadInt32(&count)
				atomic.StoreInt32(&count, value+1)
			}()
		}
		wg.Wait()
		fmt.Println(count)
	}
```
`output`:
```
94
```
And it isnt return 100. I think the reason is `atomic.LoadInt32(&count)` get the same value in two different goroutine.

- `g1` execute `atomic.LoadInt32(&count)` but not add the value into the `count`
-  `g2` execute  `atomic.LoadInt32(&count)` and get the same result.

**Comment by nolouch** [comment]
@bradyjoestar Thanks. Actually, the usage of the update `step` isn't an atomic operator.  but the final result of the step is determined by the state of the region, the result of `step` is ultimately consistent. and we only use the atomic to avoid the`race` problem.

**Comment by bradyjoestar** [comment]
Thank you and I will read the ```schedule``` module ahead :grinning:
