### ISSUE TITLE
running a tikv without data and with the same ip return error

### ISSUE THREAD

**Issue by pcleon** [pingcap/pd#1461]
we have a disk error and reinstall a system with a same ip, then i want to run tikv without data exist .
1. i run "store delete 1" and then get:
`» store
{
  "count": 1,
  "stores": [
    {
      "store": {
        "id": 1,
        "address": "172.16.10.48:20160",
        "state": 1,
        "version": "2.1.4",
        "state_name": "Offline"
      },
      "status": {
        "capacity": "62 GiB",
        "available": "32 GiB",
        "leader_count": 15,
        "leader_weight": 1,
        "leader_score": 15,
        "leader_size": 15,
        "region_count": 15,
        "region_weight": 1,
        "region_score": 15,
        "region_size": 15,
        "start_ts": "2019-02-25T11:05:04+08:00",
        "last_heartbeat_ts": "2019-03-18T10:11:16.784778025+08:00",
        "uptime": "503h6m12.784778025s"
      }
    }
  ]
}`

2.then i use the same config to running tikv server ,then it shows below:
`
2019/03/18 10:23:46.510 INFO server.rs:86: listening on 172.16.10.48:20160
2019/03/18 10:23:46.510 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.511 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.511 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.511 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.511 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.512 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))
2019/03/18 10:23:46.512 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:32 address:\"172.16.10.48:20160\" version:\"2.1.4\" , already registered by id:1 address:\"172.16.10.48:20160\" state:Offline version:\"2.1.4\" ") }))`

the faq only show me to delete store id and nothing else anymore , what should i do?

**Comment by rleungx** [comment]
@pcleon Thanks for your feedback!
How many TiKV do you have?

**Comment by pcleon** [comment]
> @pcleon Thanks for your feedback!
> How many TiKV do you have?
3

**Comment by pcleon** [comment]
> @pcleon Thanks for your feedback!
> How many TiKV do you have?

3

**Comment by rleungx** [comment]
The reason why the store still exists is after you delete a store, there is no extra machine to make up the replica. Since our replica is 3, the status of the store will always be `offline` and won't become `tombstone`. So we can not add the store with the same configuration.
In this situation, we can set the max replica to 2 temporarily. After the store become `tombstone` , we can change max replica back and add the store back with the same configuration.

**Comment by pcleon** [comment]
so it is , thanks~~
