### ISSUE TITLE
Rollback config in store when kv.persist failed

### ISSUE THREAD

**Issue by bradyjoestar** [pingcap/pd#1475]
I am reading the following code
https://github.com/pingcap/pd/blob/f72cc23e5765b32c0d503e4fecd4b37fea44c98f/server/server.go#L531-L542
If `s.scheduleOpt.persist(s.kv)` returns `err`, it will not  rollback to the old config in `scheduleOpt`

Maybe we'd better add the rollback code? just like this:
```
old := s.scheduleOpt.load() 
s.scheduleOpt.store(&cfg) 
if err := s.scheduleOpt.persist(s.kv); err != nil { 
        s.scheduleOpt.store(old) 
 	return err 
 } 
```

**Comment by nolouch** [comment]
@bradyjoestar  good catch!

**Comment by bradyjoestar** [comment]
@nolouch  I will create a new pr for these similar case. :grimacing:
