### ISSUE TITLE
why only `bytes-read-rate` has value in `hot` command

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#1481]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run sysbench update_non_index with just only 1 table and 1m rows

```
» hot store
{
  "bytes-write-rate": {
    "1": 0,
    "4": 0,
    "5": 0
  },
  "bytes-read-rate": {
    "1": 2472,
    "4": 36933,
    "5": 193
  },
  "keys-write-rate": {
    "1": 0,
    "4": 0,
    "5": 0
  },
  "keys-read-rate": {
    "1": 0,
    "4": 0,
    "5": 0
  }
}
```

2. What did you expect to see?

I think `bytes-write-rate` should also have value. 

Btw, maybe `keys-read-rate` and `keys-write-rate` have value too.

3. What did you see instead?

Only `bytes-read-rate` has value, I am confused about this result.

4. What version of PD are you using (`pd-server -V`)?

```
./bin/pd-server -V
Release Version: v3.0.0-beta.1
Git Commit Hash: 57170171811130d7d39759efb9f9677aebfc03db
Git Branch: master
UTC Build Time:  2019-03-27 01:51:58
```

**Comment by rleungx** [comment]
Fixed via #1487 and tikv/tikv#4436.
