### ISSUE TITLE
[proposal] region status dashboard

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/pd#149]
pd exposes a http dashboard to show the status of each region. 

@iamxy @qiuyesuifeng

**Comment by ngaut** [comment]
Maybe just export those updating regions.

**Comment by c4pt0r** [comment]
@ngaut  if there's no updating regions, isn't that an empty page?

**Comment by ngaut** [comment]
Yes, because there are too many regions. It's difficult to display them in a single web page.

**Comment by iamxy** [comment]
Maybe those updating regions can be shown by animation，others just display summary.

**Comment by siddontang** [comment]
I think we should support Restful API https://github.com/pingcap/pd/issues/36 first, then consider the dashboard.

**Comment by iamxy** [comment]
No conflict, dashboard is more a frond-end work, and based on a set of REST api

**Comment by c4pt0r** [comment]
@siddontang agree, but I think we can work on them in parallel.

**Comment by qiuyesuifeng** [comment]
See #163

**Comment by siddontang** [comment]
Can we close it now? @c4pt0r @iamxy
