### ISSUE TITLE
support removing TiKV by address

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#1517]
I follow https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment-scale.md#decrease-the-capacity-of-a-tikv-node to remove a TiKV node and find that it is hard for users to find a store ID of TiKV.

We also use the name to delete PD https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment-scale.md#decrease-the-capacity-of-a-pd-node, so I think it is more straightforward to use the TiKV address too.

For example: `./pd-ctl -u "http://172.16.10.1:2379" -d store delete 172.16.10.9:20160`

**Comment by disksing** [comment]
There are other commands need store id too. Why not add a command to query store using address?
btw, the problem can be easily handled using `jq`:
```
#### list {id, address}
» store --jq='.stores[].store | {id, address}'
{"id":1,"address":"127.0.0.1:20161"}
{"id":2,"address":"127.0.0.1:20163"}
{"id":7,"address":"127.0.0.1:20162"}

#### query by address
» store --jq='.stores[].store | select(.address=="127.0.0.1:20161") | {id, address}'
{"id":1,"address":"127.0.0.1:20161"}
```

**Comment by siddontang** [comment]
In K8s, mostly, we don't have installed jq, another problem is that the usage of jq is not in the pd-ctl help output, it is hard for the users to use it directly.

**Comment by shafreeck** [comment]
I'd like to help to solve this if needed.

**Comment by shafreeck** [comment]
I browsed the code of `pd-server` and `pd-ctl` roughly and found that all the store information are stored in a map which indexed by the store ID. It is a natural way to manipulate the store by its ID. What we can do here is listing all the stores and filtering by its address to get the store ID. I want to make sure if this is an acceptable solution before starting the code.

Extend the delete subcommand with "addr" as the parameter
```
store delete addr <the address you want to delete>
```
