### ISSUE TITLE
why help sub command still uses readline in pd-ctl 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#1518]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
/ # ./pd-ctl help store
»
```

I just want to use `help` to see how to use the command. 

2. What did you expect to see?

I think we should also use detach mode for `help`.

3. What did you see instead?

To my surprise, it enters the readline mode.  

4. What version of PD are you using (`pd-server -V`)?

```
pd-ctl --version
Release Version: v3.0.0-beta.1-2-g56f4100
Git Commit Hash: 56f4100f9468c84bc52143e39dfafe4d17565889
Git Branch: master
UTC Build Time:  2019-03-29 09:04:23
```

**Comment by disksing** [comment]
`pd-ctl` only use detached mode when you use `-d`.  A more common approach seems to be using detached mode by default, and use `./pd-ctl -i` to use interactive mode. Then this problem is resolved.
