### ISSUE TITLE
[Question]Question About PD-Recover

### ISSUE THREAD

**Issue by XSHui** [pingcap/pd#1525]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
**Pd Recovery Simulate**
https://pingcap.com/docs-cn/tools/pd-recover/
- Pressure measurement
- Stop all pd servers
- Get cluster-id and alloc-id
- Stop tidb and tikv servers' container;
- `rm -rf pd/member`
- `./pd-recover -alloc-id=10000 -cluster-id=6685220418055349615 -endpoints=http://****:**`
- Start tikv and tidb servers' container

2. What did you expect to see?
    The cluster available

3. What did you see instead?
    Pd created a new cluster id, thus tikv and tidb servers' container can't be running

4. What version of PD are you using (`pd-server -V`)?
    pd-v2.1.4

Question:
1. Is my simulation experiment step correct? If it's not, how about the correct experimental procedure ?
2. Why a new cluster id be created?  If it's right, how to update cluster id in tidb & tikv?
3. I can't get cluster id in tikv's log.

**Comment by disksing** [comment]
Hi @XSHui , as mentioned in the doc, you need to restart PD too after using `pd-recover`.

**Comment by disksing** [comment]
Thanks for your report. The doc seems not clear enough :)
