### ISSUE TITLE
`GetMembersRequest` return success, but PDClient's clientUrls_ is empty

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/pd#1561]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`GetMembersRequest` return success, but PDClient's clientUrls_ is empty

2. What did you expect to see?
`GetMembersRequest` return success, and PDClient's clientUrls_ is not empty

3. What did you see instead?
![image](https://user-images.githubusercontent.com/5574887/58869869-a54c6b80-86f1-11e9-8c24-5ff260d7b280.png)

4. What version of PD are you using (`pd-server -V`)?
v2.1.9

**Comment by disksing** [comment]
Hi @marsishandsome , the reason is the region has no leader at that time. For protocol buffers greater than 3.0, there is no optional field any more, so you need to compare `leader` with the default value to determine if it is set.

**Comment by marsishandsome** [comment]
@birdstorm FYI
