### ISSUE TITLE
location-labels does not support Backslash symbols

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/pd#1588]
1. What did you do?
When I deploy TiDB cluster by TiDB operator on K8s, I want to use the labels which have been set in K8s node, but current PD does not support label which contains `\`. 
e.g:`failure-domain.beta.kubernetes.io/region`

2. What did you expect to see?
PD supports the label which matches K8s's label style.
ref: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

**Comment by shafreeck** [comment]
Thanks for your feedback, I will check about this.

**Comment by shafreeck** [comment]
related: https://github.com/pingcap/pd/pull/1154

**Comment by shafreeck** [comment]
the k8s style: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation.go#L42
