### ISSUE TITLE
Kettle 数据同步Job运行一段时间后，存在自停止的现象

### ISSUE THREAD

**Issue by sliver1001** [pingcap/pd#1645]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

我准备了一个数据同步的job，使用kettle运行，但是它运行一段时间后，就会出现自动停止的现象，有时候是kettle自身这个应用停掉，有时候是kettle内部运行的job停掉。
2. What did you expect to see?
我想知道，有没有哪位大佬遇到过类似情况？并且是怎么解决的呢？
日志内容：
![image](https://user-images.githubusercontent.com/41311567/61502705-825aea00-aa07-11e9-9f8d-4bc8c54e2238.png)

**Comment by disksing** [comment]
Interesting. What the relationship between this issue and PD?

**Comment by sliver1001** [comment]
I'm sorry very much！I send it in a wrong place.

**Comment by sliver1001** [comment]
I'm sorry very much！I send it in a wrong place.Sorry！



sliver1001@126.com
 
发件人： disksing
发送时间： 2019-07-19 13:01
收件人： pingcap/pd
抄送： sliver1001; Author
主题： Re: [pingcap/pd] Kettle 数据同步Job运行一段时间后，存在自停止的现象 (#1645)
Interesting. What the relationship between this issue and PD?
