### ISSUE TITLE
Question: the use the command TSO wait metrics?

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#1656]
I find the cmd metrics wait contains the time of TSO execution time:

```go
func (req *tsoRequest) Wait() (physical int64, logical int64, err error) {
	// If tso command duration is observed very high, the reason could be it
	// takes too long for Wait() be called.
	start := time.Now()
	cmdDurationTSOAsyncWait.Observe(start.Sub(req.start).Seconds())
	select {
	case err = <-req.done:
		err = errors.WithStack(err)
		defer tsoReqPool.Put(req)
		if err != nil {
			cmdFailDurationTSO.Observe(time.Since(req.start).Seconds())
			return 0, 0, err
		}
		physical, logical = req.physical, req.logical
		now := time.Now()
		cmdDurationWait.Observe(now.Sub(start).Seconds())
		cmdDurationTSO.Observe(now.Sub(req.start).Seconds())
		return
	case <-req.ctx.Done():
		return 0, 0, errors.WithStack(req.ctx.Err())
	}
}
```

As you can see, the Wait here includes getting TSO, is it proper?

**Comment by disksing** [comment]
em, what do you mean by "includes getting TSO"? The meaning of the 3 metrics here:
- cmdDurationTSOAsyncWait: from calling `GetTS` to calling `Wait`
- cmdDurationWait: from calling `Wait` to `Wait` returns.
- cmdDurationTSO: from calling `GetTS` to `Wait` returns.

**Comment by siddontang** [comment]
> cmdDurationWait: from calling Wait to Wait returns.

You can see the Wait also contains the time of getting TSO.
