### ISSUE TITLE
PCP: Improve the API about region information

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1721]
## PCP issue
- difficult: Easy
- score: 50
- min score required: 0
- recommended skills: GO
## Description
Now, TiDB uses some PD API to discover the status of the cluster, Such as the write/read information of the table. we can do some improvements on the API. and a region result as follows now: 
```
{
  "id": 2,
  "start_key": "7480000000000000FFAF5F728000000039FFC4D7830000000000FA",
  "end_key": "",
  "epoch": {
    "conf_ver": 4571,
    "version": 8348
  },
  "peers": [
    {
      "id": 668213,
      "store_id": 7
    },
    {
      "id": 668234,
      "store_id": 11
    },
    {
      "id": 668909,
      "store_id": 1
    }
  ],
  "leader": {
    "id": 668213,
    "store_id": 7
  },
  "written_bytes": 918769,
  "approximate_size": 197,
  "approximate_keys": 714305
}
```
There are some points :
- aprroximate_size: should specify the unit: `MB`
- written_bytes/read_bytes: use a weighted moving average method to smooth history changed.

**Comment by qinggniq** [comment]
@nolouch 
About point 2:
> written_bytes/read_bytes: use a weighted moving average method to smooth history changed.
means ?
1. add a field "written_bytes/read_bytes" at region info;
2. store some history value of  "written_bytes/read_bytes" to smooth history change.
any misunderstanding?

**Comment by nolouch** [comment]
@qinggniq Sorry for the late reply.  I'm going to close this because this API now used to many places, and may affect other components. I have fired a new one to replace this, you can check #1920 #1964
