### ISSUE TITLE
PCP: add region size/keys histrogram

### ISSUE THREAD

**Issue by Connor1996** [pingcap/pd#1744]
## PCP Issue

- difficult: easy
- score: 100
- min score required: 0 
- expired: 7d
- Recommended Skills:
- Mentor(s):

## Description

Maybe helpful to check whether merge works well which improves the efficiency of finding problems.

**Comment by mantuliu** [comment]
@Connor1996 @nolouch 
I want to do like this . Please help me see if the idea is correct？thanks.
-----------------------
User input like this:
```
pd-ctl region check  histogram
```

the pd-ctl output like this :

```
Response region size histogram:
  1  [1]	|
  21 [999092]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  36 [815]	|
  48 [88]	|
 59 [4]	|
 71  [0]	|
  83 [0]	|
  92 [0]	|

Response region keys histogram:
  0 [31]	|
  210000 [999092]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  310000 [815]	|
  423456 [88]	|
  523456 [4]	|
  623456 [0]	|
  723456 [0]	|
  823456 [0]	|
  923456 [1]	|
  1023456 [11]	|
  1123456 [8]	|
```

**Comment by disksing** [comment]
Please take a look @nolouch @Connor1996
