### ISSUE TITLE
when using go 1.13 the import of a specific tag fails

### ISSUE THREAD

**Issue by thinktainer** [pingcap/pd#1745]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`go get github.com/pingcap/pd@v3.0.3`

2. What did you expect to see?
expected the extract message from go get.

3. What did you see instead?
```go get github.com/pingcap/pd@v3.0.3: github.com/pingcap/pd@v3.0.3: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3```

4. What version of PD are you using (`pd-server -V`)?
3.0.3

**Comment by disksing** [comment]
Hi @thinktainer , why do you want to `go get` PD? If you want to build PD manually, you can clone the repo them `make`.

**Comment by nolouch** [comment]
Maybe we should make the go mod path consist with the release version https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher. How about TiDB? @tiancaiamao

**Comment by tiancaiamao** [comment]
I agree with that change, but it involves a moderate amount of work.
I guess many of us TiDB folks are now busy with some other higher priority things and we don't have a time schedule for it.

**Comment by thinktainer** [comment]
i need to import pd as a dependency in order to be able to use tikv.

**Comment by disksing** [comment]
Hi @thinktainer , we do not support _Semantic Import versioning_ now. You may import master branch like _pingcap/tidb_: `go get -u github.com/pingcap/pd/client@master`

**Comment by tiancaiamao** [comment]
Or try the specific PD version with `go get github.com/pingcap/pd/client@commit hash`

**Comment by thinktainer** [comment]
I am using this, but considering it a work around.

**Comment by thinktainer** [comment]
https://blog.golang.org/v2-go-modules

**Comment by rleungx** [comment]
@thinktainer You can try to use `go get github.com/pingcap/pd/v3@v3.0.14` now.

**Comment by thinktainer** [comment]
Thank you, will check it out!
