### ISSUE TITLE
Add a corresponding test name as a field to each log

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1829]
## PCP Issue

- difficult: Easy
- score: 300
- min score required: 0
- Recommended Skills: Go

## Description
We cannot confirm a log belongs to which test case when we run `go test .` in the package. maybe we can add a field named `case-name=xxxx` in the log entry to distinguish them.

**Comment by nolouch** [comment]
Hi @zhang2j, I found this issue duplicate with  https://github.com/pingcap/pd/issues/2167. I adjust the score, and would you like to pick that issue instead of this one?

**Comment by zhang2j** [comment]
ok
