### ISSUE TITLE
PCP:  Accelerate the speed of the load region

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1830]
## PCP Issue

- difficult: easy
- score: 100
- min score required: 0
- Recommended Skills:

## Description
We need to `load regions` from disk to build region cache when the new leader startup. the cost time is the gap that PD doesn't provide services(except tso service). because we use `region sycner` to sync the change of region to the follower, we can build the region cache in follower so that the new leader no need to load data from disk to reduce no service time.

**Comment by qinggniq** [comment]
give-up-challenge

**Comment by you06** [comment]
@qinggniq try "/give-up-challenge" again.
