### ISSUE TITLE
Improve the heartbeat processing

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1846]
## Description

PD collects cluster information through heartbeats, It can be said that the processing power of the heartbeat is the ceiling of the entire cluster. It is very important to improve the performance of heartbeat processing. There is a benchmark tool `pd-heartbeat-bench` in PD project, now the benchmark result like:
```
Summary:
  Total:	9.7948 secs.
  Slowest:	0.6721 secs.
  Fastest:	0.0000 secs.
  Average:	0.0002 secs.
  Stddev:	0.0057 secs.
  Requests/sec:	102097.3460

Response time histogram:
  0.0000 [1]	|
  0.0672 [999313]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.1344 [339]	|
  0.2016 [187]	|
  0.2688 [72]	|
  0.3361 [41]	|
  0.4033 [18]	|
  0.4705 [19]	|
  0.5377 [15]	|
  0.6049 [13]	|
  0.6721 [2]	|

Latency distribution:
  10% in 0.0000 secs.
  25% in 0.0000 secs.
  50% in 0.0000 secs.
  75% in 0.0000 secs.
  90% in 0.0000 secs.
  95% in 0.0000 secs.
  99% in 0.0000 secs.
  99.9% in 0.0329 secs.
```
Goals:
- Improve the heartbeat processing, expect above 300k Requests/sec with `region-update-ratio=0.1`
- Don't change the behavior of log in heartbeat path

Tasks:

- [x] [Reduce the unnecessary clone overhead in heartbeat process](https://github.com/pingcap/pd/issues/2391)
- [x] [Reduce the unnecessary update for the new region in a heartbeat](https://github.com/pingcap/pd/issues/2392)
- [ ] Optimize the storage process

## Difficulty

- Medium

## Score

- 3488

## Mentor(s)

- @nolouch 

## Recommended Skills

- Go

**Comment by wangrzneu** [comment]
What is the test environment where you got the test result?
