### ISSUE TITLE
api: `map` type in RAML

### ISSUE THREAD

**Issue by Luffbee** [pingcap/pd#1853]
RAML does not support `map` type directly. So there are several type information cannot be described properly.

I find that there is feature in RAML that support property names by regular expression: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#additional-properties
Maybe we can use this feature to support `map` with `string` or `integer` key?

**Comment by disksing** [comment]
Please accept my admiration 👍  I think we can do it!

**Comment by rleungx** [comment]
Since we have already use swagger to manage the API docs, close it.
