### ISSUE TITLE
dynamic set rebalance speed with API

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/pd#186]
Assume our Database contain many GB or TB datas, when we start our tikv nodes one by one, the earlier started nodes will campaign election earlier than others and win the election then become region leader, result in most regions' leader located at few nodes. What we want is the leader transfer from these few nodes to others as soon as possible, so we need high rebalance speed. But when the DB is providing OLTP services, we should limit the rebalance speed.

**Comment by qiuyesuifeng** [comment]
See #188 
I think in our algorithm, we can try to do balance first, but if the balance condition is not matched, we can try another way that is only leader transfer.
In your scenario,  this strategy can work well.
So how do you think of this? Any other suggestions?
@zhangjinpeng1987  @shenli  @siddontang

**Comment by siddontang** [comment]
I guess @zhangjinpeng1987 wants to adjust the speed dynamically, e.g, now we do auto-balance every 10s, but we can reduce or increase this, like every 1s or every 30s dynamically.
