### ISSUE TITLE
gc dead store

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#189]
If the store was down, pd should be told about it or pd should check whether the store is alive or not for a long time. 

If pd ensures that the store is down, it will do balance for the region which contains the store, maybe we can do it in following cases:

+ When the leader of region reports Heartbeat, pd finds the region contains the dead store and then does balance. 
+ Pd chooses a region which contains the dead store regularly, then does balance.

/cc @qiuyesuifeng @disksing @zhangjinpeng1987

**Comment by huachaohuang** [comment]
This issues will be separated into three steps:

- [ ] Health check for stores and filter out down stores from balance.
- [ ] Health check for regions and do balance for down peers. [tikv #823](https://github.com/pingcap/tikv/issues/823)
- [ ] Add admin api to remove stores gracefully.
