### ISSUE TITLE
update region information on etcd asynchronously.

### ISSUE THREAD

**Issue by qiuyesuifeng** [pingcap/pd#192]
In our implementation, we update etcd synchronous if the region information is changed.
Now we only use pd for quick recover, so it is better to make update asynchronously.

/cc @siddontang @disksing

**Comment by disksing** [comment]
Now region info is saved to etcd only its epoch is updated (split/addPeer/removePeer), which is not frequently happen. Also now the saving process doesn't acquire lock, see https://github.com/pingcap/pd/pull/677
So I see no reason to make asynchronously.
