### ISSUE TITLE
add more metrics for etcd

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#193]
We should add more metrics. Like

+ etcd transaction duration. 
+ etcd transaction counter, error counter, not success counter. 
+ generate id counter.
+ generate TSO counter.  

Anything to add?
/cc @qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
Also we should monitor the cost time of random region function.
Now we only used a log for it, later we can move it to metrics too.
