### ISSUE TITLE
follower's metrics cause wrong alerts

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/pd#1934]
1. What did you do?
When pd leader transfer from host A to host B, prometheus can also pull metrics from A, thus result to wrong alerts, such as `sum(pd_cluster_status{type="store_disconnected_count"}) > 0`.

2. What did you expect to see?
It's better for prometheus only pull metrics from pd's leader. 

3. What did you see instead?

4. What version of PD are you using (`pd-server -V`)?
`pd-server --version`
Release Version: v4.0.0-alpha-78-g2550168c
Git Commit Hash: 2550168c27878a33a8465a72bafdc534e409b60a
Git Branch: master
UTC Build Time:  2019-10-11 03:00:20

**Comment by rleungx** [comment]
#1790 will reset the metrics once the leader steps down. I think this may solve this problem?

**Comment by fredchenbj** [comment]
@rleungx Yes, `clusterStatusGauge.Reset()` would reset the metric `pd_cluster_status{type="store_disconnected_count"}`, then solved this problem. Which release version of pd have cherry-picked this patch?

**Comment by rleungx** [comment]
This fix was landed from v3.0.5. Close it for now and feel free to reopen it if you still have problems
