### ISSUE TITLE
testServerSuite depends on /tmp/test_pd_check_clusterID_0/.touch

### ISSUE THREAD

**Issue by Luffbee** [pingcap/pd#1946]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Use PD with the fix PR #1945 (or the test will be blocked), and execute the following commands with a normal user.
``` bash
sudo mkdir /tmp/test_pd_check_clusterID_0
cd ${PD_SRC_ROOT}/server
go test -check.f testServerSuite
```

2. What did you expect to see?

Test pass.

3. What did you see instead?

```
FAIL: server_test.go:152: testServerSuite.TestCheckClusterID

server_test.go:128:
    c.Assert(err, IsNil)
... value *errors.withStack = cannot access data directory: open /tmp/test_pd_check_clusterID_0/.touch: permission denied ("cannot access data directory: open /tmp/test_pd_check_clusterID_0/.touch: permission denied")
```
4. What version of PD are you using (`pd-server -V`)?

PR #1945

**Comment by disksing** [comment]
Is can not occur in real env. Closing.
