### ISSUE TITLE
PCP:  Imporve the grant leader scheduler with http handler

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#1964]
## PCP Issue

- difficult: easy
- score: 100
- min score required: 0
- Recommended Skills: Go

## Description
We have supported the scheduler configures the own configuration after #1733 . The grant leader scheduler should add multiple schedulers if we want to grant multiple stores. but now we can support multiple args in one scheduler.  same as #1937.

**Comment by you06** [comment]
Hi @qinggniq , there was something wrong with the picking up task, but don't worry, your pick up is under review stage in #1968 now(hrbeuyz24 is your partner). I add some logs for solving the picking up issue, may you try picking up again and let me find out what's wrong with it?

**Comment by you06** [comment]
Soon after you've gave up 1830, your partner picked it up. And before he submitting a PR for 1830, your team is under doing pick status which not allow you to pick up a second one. And I got a mistake that 1968 is the solution for 1830 instead of this issue.

**Comment by qinggniq** [comment]
@you06 got it, thank you!

**Comment by you06** [comment]
Bot closed... that's weird, sorry for the incident. Reopen it and I'll try finding out the problem.

**Comment by nolouch** [comment]
finished.
