### ISSUE TITLE
The sum of label distribution is not equal to the store number

### ISSUE THREAD

**Issue by gengliqi** [pingcap/pd#2004]
1. What did you do?
After rolling updating from 2.1.15 to 3.0.7, the sum of label distribution is not equal to the store number.

![image](https://user-images.githubusercontent.com/21253569/70526932-a3be9d00-1b85-11ea-879f-01c85023ad73.png)

2. What did you expect to see?
The sum of label distribution should equal to the store number

3. What version of PD are you using (`pd-server -V`)?
v3.0.7

**Comment by disksing** [comment]
Please take a look @rleungx @nolouch

**Comment by nolouch** [comment]
fixed.
