### ISSUE TITLE
region size/keys histogram format

### ISSUE THREAD

**Issue by lhy1024** [pingcap/pd#2036]
After #2014, we supported region size/keys histogram.
Their format:
```
{
"[0,10000)": 1000020,
"[200000,210000)": 50055,
"[210000,220000)": 49702,
"[220000,230000)": 50162,
"[230000,240000)": 50392,
"[240000,250000)": 49935,
"[250000,260000)": 49662,
"[260000,270000)": 50302,
"[270000,280000)": 49778,
"[280000,290000)": 50155,
"[290000,300000)": 49838,
"[300000,310000)": 49715,
"[310000,320000)": 50019,
"[320000,330000)": 50076,
"[330000,340000)": 50040,
"[340000,350000)": 50178,
"[350000,360000)": 49887,
"[360000,370000)": 49910,
"[370000,380000)": 50011,
"[380000,390000)": 49977,
"[390000,400000)": 50226
}
```
I just realized that this format may not conform to the principle of json self-explanation. how about `{"start":0,"end":10000,"count":1000020}` @mantuliu

**Comment by disksing** [comment]
+1

**Comment by mantuliu** [comment]
@lhy1024 @disksing There is a problem, the opening and closing interval cannot be expressed, for example:
{
"start":0,"end":10000,"count":1000020,
"start":10000,"end":20000,"count":0,
}
Can you accept this style? if you can,I will do like the example.

**Comment by lhy1024** [comment]
> @lhy1024 @disksing There is a problem, the opening and closing interval cannot be expressed, for example:
> {
> "start":0,"end":10000,"count":1000020,
> "start":10000,"end":20000,"count":0,
> }
> Can you accept this style? if you can,I will do like the example.

Good, how about 
```
{
{"start":0,"end":9999,"count":1000020},
{"start":10000,"end":20000,"count":0},
}
```

**Comment by disksing** [comment]
```
[
    {"start":0,"end":9999,"count":1000020},
    {"start":10000,"end":20000,"count":0},
    ...
]
```
