### ISSUE TITLE
combine flag default value and config default value

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#207]
now we define many default values for configs, but at same time, we use another ones for flags. But they are same, so we can combine these in one place. 

Maybe we can add a Flag field config like etcd. 

/cc @qiuyesuifeng @huachaohuang

**Comment by qiuyesuifeng** [comment]
+1, aggreed.
@huachaohuang

**Comment by huachaohuang** [comment]
Yep, I will refactor it with #198 .
