### ISSUE TITLE
Unstable performance of sysbench oltp_update_index benchmarking

### ISSUE THREAD

**Issue by mahjonp** [pingcap/pd#2072]
1. What did you do?

PR #2065 may Introduced a bug that cause the unstable performance of oltp_update_index workload.

![image](https://user-images.githubusercontent.com/3251373/71640403-50db8f80-2cc4-11ea-8e55-999ce62fb9a5.png)

You can reproduce it with sysbench running oltp_update_index method with master tidb, master tikv and pd commit hash: 26ba96dda430182eb8a980a9f69c5e6ac1313932

```bash
sysbench oltp_update_index --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=sbtest --time=240 --mysql-ignore-errors=all --report-interval=10 --db-driver=mysql --threads=256 --percentile=99 --warmup-time=60 --rand-type=special --tables=32 --table-size=1000000 run
```

**Comment by disksing** [comment]
@mahjonp It is very unlikely that this PR has performance issue. I wonder how did you nail down to this PR...
/cc @rleungx

**Comment by mahjonp** [comment]
> @mahjonp It is very unlikely that this PR has performance issue. I wonder how did you nail down to this PR...
> /cc @rleungx

You could see that the performance was stable in b361283, but it became unstable from 26ba96d.

26ba96d: https://internal.pingcap.net/idc-jenkins/view/bench_bot/job/bench_sysbench_per_pr/841/consoleFull
b361283: https://internal.pingcap.net/idc-jenkins/view/bench_bot/job/bench_sysbench_per_pr/838/consoleFull

**Comment by rleungx** [comment]
PR #2065 only changes the config output problem, which is not related to performance. @mahjonp
