### ISSUE TITLE
Use golangci-lint in the officially recommended way, and add configuration files.

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/pd#2129]
### Describe your feature request related problem: 

* The current way of using golangci-lint is not officially recommended, and it is not guaranteed to be a release version.
* The current configuration items are written in the makefile in the form of a command line and cannot be used by IDEs that support golangci-lint.

### Describe the feature you'd like:

* Use golangci-lint in the [officially recommended way](https://github.com/golangci/golangci-lint#binary).
* Add a `.golangci.yml` file to this project.

**Comment by rleungx** [comment]
Done via #2195.
