### ISSUE TITLE
go example not working

### ISSUE THREAD

**Issue by FlorianLudwig** [pingcap/pd#2148]
Compiling the example "Usage example of the Transactional Key-Value API" from https://tikv.org/docs/3.0/reference/clients/go/

2. What did you expect to see?

No compile error.

3. What did you see instead?

```
build command-line-arguments: cannot load github.com/pingcap/pd/pd-client: module github.com/pingcap/pd@latest found (v2.1.19+incompatible), but does not contain package github.com/pingcap/pd/pd-client
```

**Comment by disksing** [comment]
Please take a look @shafreeck

**Comment by shafreeck** [comment]
Sorry for the trouble because of our outdated documentation.
The importing path `"github.com/pingcap/tidb/terror"` is outdated. It causes `go mod` to download and build the old version of TiDB (`v2.0.11+incompatible`). The old version TiDB uses the package `pd-client`  which has been renamed to `client`.

**Comment by FlorianLudwig** [comment]
@shafreeck thank you for taking a look at this, but even with those changes I am getting the same error.

```
$ go run test.go 
go: downloading github.com/juju/errors v0.0.0-20190930114154-d42613fe1ab9
go: downloading golang.org/x/net v0.0.0-20191002035440-2ec189313ef0
go: downloading github.com/pingcap/tidb v2.0.11+incompatible
go: downloading github.com/pingcap/parser v0.0.0-20200218113622-517beb2e39c2
[...]
go: extracting github.com/pingcap/tidb v2.0.11+incompatible
[...]
build command-line-arguments: cannot load github.com/pingcap/pd/pd-client: module github.com/pingcap/pd@latest found (v2.1.19+incompatible), but does not contain package github.com/pingcap/pd/pd-client
```

**Comment by shafreeck** [comment]
Maybe we should rebuild the environment.

* clean the go mod cache `go clean -modcache`
* get the master of tidb: `go get github.com/pingcap/tidb@master`

**Comment by FlorianLudwig** [comment]
@shafreeck thanks! works for me now too

**Comment by yanghaitao0** [comment]
@shafreeck 

> Maybe we should rebuild the environment.
> 
> * clean the go mod cache `go clean -modcache`
> * get the master of tidb: `go get github.com/pingcap/tidb@master`

I did that, but still get the same error
github.com/pingcap/pd/pd-client: module github.com/pingcap/pd@latest found (v2.1.19+incompatible), but does not contain package github.com/pingcap/pd/pd-client

**Comment by shafreeck** [comment]
Did you update to use `github.com/pingcap/parser/terror`?

**Comment by cycmay** [comment]
> I did that, but still get the same error

I did that, but still get the same error

**Comment by disksing** [comment]
Hi @cycmay Please use `client-go v2` https://github.com/tikv/client-go
