### ISSUE TITLE
LeaderCount value of StoreStatus type of The Store recommends not set auto-hide.

### ISSUE THREAD

**Issue by superlzs0476** [pingcap/pd#2156]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- If possible, provide a recipe for reproducing the error.
When I am execting rolling_update for tikv-server, but ansible can not find leader_count with PD's metadata.so that executed failed.

TiDB-Ansible Error
```log
ERROR MESSAGE SUMMARY **************************************************************************************************************************************
[tikv146_20172]: Ansible FAILED! => playbook: rolling_update.yml; TASK: check tikv's leader count; message: {"msg": "The conditional check '(store_info.json.status.leader_count is defined and store_info.json.status.leader_count|int < 1) or store_info.json.status.leader_count is not defined' failed. The error was: error while evaluating conditional ((store_info.json.status.leader_count is defined and store_info.json.status.leader_count|int < 1) or store_info.json.status.leader_count is not defined): 'dict object' has no attribute 'json'"}
```

2. What did you expect to see?

LeaderCount value of StoreStatus type of The Store recommends not set auto-hide when Leader_count is zero.

3. What did you see instead?

When I retry rolling_update for this tikv-server of tikv146_20172, that success.

4. What version of PD are you using (`pd-server -V`)?

v3.0.5

**Comment by disksing** [comment]
Good idea.
