### ISSUE TITLE
UCP: Support Dashboard UI under windows

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/pd#2179]
## Description

Currently, [TiDB Dashboard](https://github.com/pingcap-incubator/tidb-dashboard) is integrated into PD. Among them, the way of UI integration is to download from [releases](https://github.com/pingcap-incubator/tidb-dashboard/releases). There are only [bash script](https://github.com/pingcap/pd/blob/master/scripts/embed-dashboard-ui.sh) in PD. We need to implement a ps1 script with the same effect.

## Score

* 50

## Mentor

* @hundundm

## Recommended Skills

* make
* bash script
* powershell script

**Comment by ccw1996** [comment]
I already make a pull request on https://github.com/pingcap/pd/pull/2397
