### ISSUE TITLE
UCP: Use tools.go instead of retool

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/pd#2182]
## Description

Currently, PD uses [retool](https://github.com/twitchtv/retool) to manage build tools. We need to replace it with the [officially recommended method](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module). At the same time, we need to clean up tools that are no longer used.

## Score

* 50

## Mentor

* @nolouch 
* @hundundm

## Recommended Skills

* Golang

**Comment by you06** [comment]
@loxp try again please
