### ISSUE TITLE
UCP: Query single parameters value in pd-ctl

### ISSUE THREAD

**Issue by rleungx** [pingcap/pd#2228]
## Description

After we enable the dynamic configuration change, we can use the following method the check the component parameters by using `pd-ctl`:

```
>> component ids tikv
[
    "127.0.0.1:20160",
    "127.0.0.1:20161",
]

>> component show 127.0.0.1:20160
...
[coprocessor]
  batch-split-limit = 10
  region-max-keys = 1440000
  region-max-size = "144MiB"
  region-split-keys = 960000
  region-split-size = "96MiB"
  split-region-on-table = false

[gc]
  batch-keys = 512
  max-write-bytes-per-sec = "0KiB"
  ratio-threshold = 1.1
...
```
But here are too many parameters, we should support querying a single parameter for `component` subcommand in `pd-ctl`.

## Score

- 150

## Recommended Skills

- Golang

**Comment by wq1019** [comment]
do you mean that?
```
>> component ids tikv
[
    "127.0.0.1:20160",
    "127.0.0.1:20161",
]

>> component show 127.0.0.1:20160  batch-split-limit
...
[coprocessor]
  batch-split-limit = 10

[gc]
  batch-split-limit  = 512
```

**Comment by rleungx** [comment]
Yes.

**Comment by wq1019** [comment]
I wonder if the `/ component` API can support querying a single parameter? Or can you tell me what API can be used to complete this task? If there is no relevant interface, I think I can only filter the return value of this interface to fulfill this requirement.

https://github.com/pingcap/pd/blob/b8f1ed759cddd6aaa45f3166b892f92da0cb704a/server/api/middleware.go#L243-L269

**Comment by rleungx** [comment]
It seems there is no way to query a single parameter through `/component` API since it uses grpc-gateway. I think one option is to handle this in `pd-ctl` only.

**Comment by wq1019** [comment]
I tried to parse the return value of the API into the map, and then loop to match the parameters. This method is a bit cumbersome. Do you have any good way?

**Comment by rleungx** [comment]
Since it's a map, maybe we don't need to loop?

**Comment by wq1019** [comment]
@sre-bot /assign
