### ISSUE TITLE
UCP: Combine the store balance rate and store limit

### ISSUE THREAD

**Issue by rleungx** [pingcap/pd#2245]
## Description

Currently, we have a config item named `store-balance-rate` to control the balance speed of a store. This item will initialize the store limit when the server starts or restarts. We use `limit [<store_id>|<all> <rate>]` in pd-ctl to set the store limit when the pd is running and the setting state is not persistent. When the pd is restarted, the value will back to the value of `store-balance-rate`. 
Since we need to use two ways to control the store limit, it might be confused sometimes and not friendly enough. These two ways can be combined.

## Score

- 200

## Mentor

@rleungx 

## Recommended Skills

- Golang

**Comment by rleungx** [comment]
@ccw1996 Hi, have you already started it? If not, I am going to do it, otherwise, I can provide some help if you need it since this issue has high priority. One way to do it is that we can persist the store limit in etcd.

**Comment by ccw1996** [comment]
> @ccw1996 Hi, have you already started it? If not, I am going to do it, otherwise, I can provide some help if you need it since this issue has high priority. One way to do it is that we can persist the store limit in etcd.

hi, i am trying to deal with it. But if you want to do it, you can do first. These day i'm busying with my work.  I think if use pd-ctl, update the value of store-balance-rate. It can sync the config.

**Comment by ccw1996** [comment]
@rleungx

**Comment by rleungx** [comment]
Got it. You can join our scheduling SIG slack channel. Details can be found in https://github.com/pingcap/pd/projects/5
