### ISSUE TITLE
export region status through api

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#231]
Now we can get only region meta information through api, we can't get region status.

**Comment by siddontang** [comment]
but if we have 10w+ regions, how do we get real region status for one region?

**Comment by qiuyesuifeng** [comment]
We have a restful api for region meta info, but if the region count is too many, we should use storage instead of cache.

**Comment by siddontang** [comment]
I don't think we need storage if only saving 10w regions, memory is enough.

**Comment by huachaohuang** [comment]
I think we should let user know what regions are abnormal, and what actions are we taking to handle that.

**Comment by siddontang** [comment]
So we should use another API to do this.
