### ISSUE TITLE
support removing pd

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#235]
Now we can only use etcd's API to remove pd, see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#remove-a-member

But we should hide etcd concept for user. we can support removing pd with name. 

DELETE http://127.0.0.1:9090/api/v1/members/name

/cc @qiuyesuifeng

**Comment by overvenus** [comment]
closed via #245
