### ISSUE TITLE
When the key parameter is used in the http service of pd, hex format should be used

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/pd#2351]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

* Visit in browser
`http://<PD_ADDRESS>/pd/api/v1/region/key/t%80%00%00%00%00%00%00%FF1_r%80%00%00%00%00%FF%9F2f%00%00%00%00%00%FA`
> hex format: `7480000000000000ff315f728000000000ff9f32660000000000fa`
* Execute 
`pd-ctl -u http://<PD_ADDRESS> region key 7480000000000000ff2f5f728000000000ff726b5e0000000000fa`

2. What did you expect to see?

* Get region information

3. What did you see instead?

* Url can only be accessed through tools such as `curl` and Postman, not through a browser. The reason is that the character whose Ascii code is 0 is illegal in the url, even if it has escaped to `%00`.
* `pd-ctl` will get `Failed to get region: [404] 404 page not found`.

4. What version of PD are you using (`pd-server -V`)?

* Release Version: v4.0.0-rc-12-g8438f3fc
* Git Commit Hash: 8438f3fc004da1bff7442229e53fe4272f74ce2d
* Git Branch: master

I think we need to use hex format here.

**Comment by rleungx** [comment]
Close it since #2399 has been merged, for hex format, we may need to design the API v2 in the future. And feel free to reopen it.
