### ISSUE TITLE
Can't begin evict leader when TLS between components is enabled

### ISSUE THREAD

**Issue by weekface** [pingcap/pd#2362]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I created a TiDB cluster with [TLS enabled between components](https://pingcap.com/docs/stable/how-to/secure/enable-tls-between-components/) in [tidb-operator](https://pingcap.com/docs/tidb-in-kubernetes/stable/enable-tls-between-components/).

but i failed to [upgrade](https://pingcap.com/docs/tidb-in-kubernetes/stable/upgrade-a-tidb-cluster/) the TiKV instances, the upgrade process will evict the leaders before restart the TiKV instance.

2. What did you expect to see?

evict leader succeed.

3. What did you see instead?

failed to evict leader:

```
Post https://db-pd-0.db-pd-peer.tidb1252078906480005120.svc:2379/pd/api/v1/scheduler-config/evict-leader-scheduler/config: x509: certificate signed by unknown authority
```

4. What version of PD are you using (`pd-server -V`)?

`nightly`

**Comment by nolouch** [comment]
Fix in https://github.com/pingcap/pd/pull/2368
