### ISSUE TITLE
updating label key should increase replication version

### ISSUE THREAD

**Issue by BusyJay** [pingcap/pd#2386]
Otherwise, there is no way to tell if the region is consistency over the old label key or the new label key.

**Comment by BusyJay** [comment]
Actually changing label key is very dangerous that TiKV doesn't have a safe way to update the key. We better not support updating it at all.

**Comment by disksing** [comment]
@BusyJay I think we can switch to sync_recover when key is changed.

**Comment by BusyJay** [comment]
No, TiKV doesn't support changing label key.
