### ISSUE TITLE
UCP: Reduce the unnecessary updateStoreStatusLocked call counts in heartbeat process

### ISSUE THREAD

**Issue by mantuliu** [pingcap/pd#2395]
## Score
- 200

## Mentor
- @nolouch 

## Recommended Skills
- go

## Learning Materials
Ref #1846

**Comment by nolouch** [comment]
thanks!

**Comment by you06** [comment]
@mantuliu try again please~

**Comment by nolouch** [comment]
Is this issue already finished? @mantuliu

**Comment by mantuliu** [comment]
@nolouch already finished.
