### ISSUE TITLE
pd-recover should be included in the pd docker image

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/pd#2402]
### Describe your feature request related problem: 

There is no dedicated download link for pd-recover and no binary in the docker image, it's not easy for Kubernetes users to get the pd-recover binary.
### Describe the feature you'd like:

pd-recover should be included in the pd docker image.

**Comment by Jy-poi** [comment]
I found in pingcap/pd:v6.1.0 and some newer docker image, there are no pd-recover and jq binary in the docker image. why?

**Comment by Jy-poi** [comment]
> I found in pingcap/pd:v6.1.0 and some newer docker image, there are no pd-recover and jq binary in the docker image. why?
> 
> @rleungx

I build docker myself on tag v6.1.0，it has pd-recover and jq.
