### ISSUE TITLE
replica_checker: replace down replica may violate location labels

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#2418]
when a store is down, PD selects the _best_ target store to replace the down replica. The problem is, the best target may not as good as the original one, so the isolation level will be decreased.

example: consider a cluster deployed to 3 DCs, and each DC has 2 stores:
dc1: store1, store2
dc2: store3, store4
dc3: store5, store6

suppose we have a region that replicates over 3 DCs, its peers are located in store1, store3, store5. When store1 is down, the best replacement will be store2. However, if store2 is almost full or busy, PD will select store4 or store6 as the _best_ one, then after the operator is finished, the region does not replicate over 3 DCs any more.

how to fix: we may introduce a new option to control the behaivour: allow decrease isolation level or don't allow it.

**Comment by MimeLyc** [comment]
refresh
