### ISSUE TITLE
redirect request to real leader

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#243]
Like etcd, if we send request to a follower, the follower will redirect the request to leader instead. 
But the redirect may have two ways:

+ follower returns 301 and let client to redirect to leader
+ follower proxy the command to leader

We should check which etcd uses, and determine which we should use.

/cc @ngaut  @qiuyesuifeng @huachaohuang

**Comment by ngaut** [comment]
I prefer option 2 in case of isolation of client and  pd leader.

**Comment by huachaohuang** [comment]
Should we redirect both api and rpc requests, or just api requests?

**Comment by qiuyesuifeng** [comment]
I think just http api request is OK now.
