### ISSUE TITLE
how to re-join the cluster when restart.

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#247]
Now we support static initial cluster and dynamic join cluster, for a server, if crashed, sometimes users may start the PD directly with same arguments before.So we may meet following cases:

Assume we start pd 1, 2, 3 with initial cluster way, and join pd 4 later.
+ 1 restarts, but 1's initial_cluster has only 1, 2, 3  can 1 re-join the cluster directly with origin initial_cluster?
+ 4 restarts, 4 can check if it still in cluster, so won't call Add member API. 
+ Any other cases?

/cc @iamxy @v01dstar

**Comment by overvenus** [comment]
closed via #249
