### ISSUE TITLE
Fast timeout operator when leader changed

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#2493]
### Describe your feature request related problem: 

If the leader changed cause by TiKV(maybe too busy or network problem), the operator cannot step to the final state, such as
```
PD:
try to remove peer 24
TiKV:
reject remove peer 24 because it is a leader.
``` 
Then the operator needs 10mins to timeout, which may cause the rule sync learner became slow.
### Describe alternatives you've considered:

We can check if the peer is the leader then fast timeout the operator.
### Teachability, Documentation, Adoption, Migration Strategy:

- Go

**Comment by disksing** [comment]
Looks too tricky. How about TiKV attach some info in heartbeat to cancel the operator explicitly?

**Comment by nolouch** [comment]
In my patch, I will check the step safety before sending it to TiKV. If the step is to remove the peer and the region leader is the same as the peer,  we can cancel the operator. but it only solves this one situation.
