### ISSUE TITLE
Got too many pings from the client, closing the connection.

### ISSUE THREAD

**Issue by lhy1024** [pingcap/pd#2495]
When TiDB calls PD-client to access PD, although the network is normal and the PD load is normal, such [logs](https://asktug.com/t/topic/34940/8) still appear.
```
transport: Got too many pings from the client, closing the connection.
```
It may be related to keep-alive.

**Comment by HunDunDM** [comment]
duplicate [#17870](https://github.com/pingcap/tidb/issues/17870)
