### ISSUE TITLE
proposal: add new replication config to isolate replicas explicitly and forcibly

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#2528]
### Describe your feature request related problem
https://github.com/pingcap/pd/issues/2418

### Describe the feature you'd like
Add a new config `isolation-label` (type: string).
When `isolation-label` is set, PD checkers do not consider `location-labels` any more. Instead, PD makes sure replicas of a region be isolated by the specified label.
For example, with `isolation-label = zone`, PD ensure that all replicas be placed in different zones. Even if a zone is down, PD will not try to make up replicas in other zone.

**Comment by JmPotato** [comment]
So the `isolation-label` will be strictly enforced even the replicas may stay in a state where less than three? Do we already have a mechanism now to check whether a satisfied store is back online in this situation or we have to do some extra work?

**Comment by disksing** [comment]
Yes and yes.

**Comment by JmPotato** [comment]
@disksing My current thought is to add a config named `isolation-label` and do some work in `ReplicaChecker`'s selector. `selectBestPeerToAddReplica` will return `nil` if no target meets this isolation rule. In this way both this new strict rule is added and regularly checking will be guaranteed.

**Comment by disksing** [comment]
> @disksing My current thought is to add a config named `isolation-label` and do some work in `ReplicaChecker`'s selector. `selectBestPeerToAddReplica` will return `nil` if no target meets this isolation rule. In this way both this new strict rule is added and regularly checking will be guaranteed.

Good idea. Do you want to do it? I'm refactoring the `replicaChecker`, you may want to help to review https://github.com/pingcap/pd/pull/2610 and fix this issue afterwards.

**Comment by JmPotato** [comment]
> > @disksing My current thought is to add a config named `isolation-label` and do some work in `ReplicaChecker`'s selector. `selectBestPeerToAddReplica` will return `nil` if no target meets this isolation rule. In this way both this new strict rule is added and regularly checking will be guaranteed.
> 
> Good idea. Do you want to do it? I'm refactoring the `replicaChecker`, you may want to help to review #2610 and fix this issue afterwards.

Yeah. Glad to help!

**Comment by JmPotato** [comment]
@disksing What if `isolation-label` is conflicted with a placement rule? Should `isolation-label` only be guaranteed in `replica_checker` than `rule_checker`? IMO, a placement rule has a higher priority. Maybe  `rule_checker` shouldn't consider this `isolation-label`.

**Comment by disksing** [comment]
I think we can add `isolation-label` config for each rule config (just what we did about `location-labels`). However, in the first step, I think you can just ignore placement rules, only consider when placement rule is disabled.

**Comment by MimeLyc** [comment]
update

**Comment by MimeLyc** [comment]
refresh
