### ISSUE TITLE
embed prometheus node exporter? 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#254]
Now we use prometheus and https://github.com/prometheus/node_exporter is very helpful for use to monitor the system. 

But we should deploy another service to do it, maybe we can embed this in PD and TiDB directly, so that we can use "/metrics" to see the system metrics too.

Is it ok to do this? and node_exporter may reduce our service if embedding? 

/cc @xiang90 @qiuyesuifeng @shenli @iamxy

**Comment by xiang90** [comment]
open up an issue in their repo (https://github.com/prometheus/node_exporter) and cc beorn7.
