### ISSUE TITLE
Is it possible to show scheduler details  in API?

### ISSUE THREAD

**Issue by cofyc** [pingcap/pd#2550]
### Describe your feature request related problem

Since v3.1.0, I found the schedulers List API returns `evict-leader-scheduler` instead of `evict-leader-scheduler-<storeID>`.

In the previous versions, we extract the store ID from the scheduler name to detect which store is being evicted. 

### Describe the feature you'd like

I would suggest PD can expose scheduler details.

**Comment by rleungx** [comment]
@cofyc Maybe you can try to use `curl http://127.0.0.1:2379/pd/api/v1/scheduler-config/evict-leader-scheduler/list`. 
Here is an example:
```
$ curl http://127.0.0.1:2379/pd/api/v1/scheduler-config/evict-leader-scheduler/list
{
  "store-id-ranges": {
    "1": [
      {
        "start-key": "",
        "end-key": ""
      }
    ],
    "2": [
      {
        "start-key": "",
        "end-key": ""
      }
    ]
  }
}
```

**Comment by cofyc** [comment]
Thanks! We can switch to this API.

**Comment by cofyc** [comment]
I guess this API exists both in 3.1.x and 4.x?

**Comment by rleungx** [comment]
Yes.

**Comment by cofyc** [comment]
Great!
