### ISSUE TITLE
Add related regions to priority check queue when placement rule is updated

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#2594]
## Development Task
Like #2593, while we can do it automatically. When a rule is updated, the regions belong to its range or its privious version's range may need to fix.

**Comment by Yisaer** [comment]
After the rule updated, I think we can scan the regions of the new version key range and throw these regions into Accelerate queue. WDYT? @disksing

**Comment by disksing** [comment]
> After the rule updated, I think we can scan the regions of the new version and old version key range regions and throw these regions into Accelerate queue. WDYT? @disksing

Yes, it is the basic idea. Please also note that currently the accelerated queue is implemented as a simple map of `RegionInfo`s, which may not be suitable for handling a lot of regions. On one hand, it may be too many for the `coordinator` to patrol all regions at once. On the other hand, regions may become stale because of splitting or merging. A better implementation could be storing key range directly and coordinator can scan accelerated key ranges before normal key ranges.

**Comment by Yisaer** [comment]
It seems we could add a new Attribute like `suspectKeyRanges`. During patrol regions, coordinator will patrol the regions in following order: check suspectRegions, check suspect key-ranges, patrol normal regions.

**Comment by disksing** [comment]
> It seems we could add a new Attribute like `suspectKeyRanges`. During patrol regions, coordinator will patrol the regions in following order: check suspectRegions, check suspect key-ranges, patrol normal regions.

I think that would be a good idea.
