### ISSUE TITLE
Balance leader does not consider rule constraints

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#2607]
### What did you do?

we do some tests with placement rules and the rules are like:
There are 50 partitions, and the constraints are the leader of each partition's region should be in the same store.
The state is unable to meet the constraints because the balance leader scheduler is always running：
![image](https://user-images.githubusercontent.com/6428910/86392422-061bee00-bcce-11ea-9f23-c64d2bee5a6a.png)

### What did you expect to see?
The state finally meets the rules.

### What did you see instead?
The `balance-leader· has been doing scheduling conflicts with the rule

### What version of PD are you using (`pd-server -V`)?
master

**Comment by Yisaer** [comment]
I think we could add an extra filter for the balance-leader-scheduler to take care of the placement rules. @nolouch  Could you provide the rule example in this case?

**Comment by disksing** [comment]
You got it. You may need a new type of `PlacementGuard`, and the difference is that it considers leader change instead of peer change.
