### ISSUE TITLE
interface: scanRegions couldn't get the peeding peer info of these regions

### ISSUE THREAD

**Issue by AilinKid** [pingcap/pd#2613]
## Bug Report

when pdClient `scanRegions` by tableID/partitionID
The result couldn't get peeding peer info of these regions of the table/partition.

### What did you do?

nothing

### What did you expect to see?
That will be convinent if it can scan once and get all we want (here for peeding peer info of these scanned regions)

### What did you see instead?
By now the step is:
1: scan regions
2: for every region use the ID to `getRegionByID` again to get the peeding peer info.

### What version of PD are you using (`pd-server -V`)?
master & rest

**Comment by AilinKid** [comment]
PTAL @disksing

**Comment by disksing** [comment]
@AilinKid This issue is fixed by https://github.com/pingcap/pd/pull/2649
