### ISSUE TITLE
the cost of leader change

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#262]
Now if a PD node becomes leader, it will load all stores and regions metas first from etcd, if we have many regions, we can't bear leader changing frequently. 
Maybe we should think another way to handle cluster initialization. 

/cc @qiuyesuifeng @huachaohuang @overvenus

**Comment by siddontang** [comment]
Hi @huachaohuang 

We can add some results here, for loading about 300000 regions or even more.

**Comment by huachaohuang** [comment]
Here are some results we benched on an 8 cores SSD machine so far:
For 300,000 regions, it costs 1.3s.
For 3,000,000 regions, it costs 13s.
