### ISSUE TITLE
Support get cluster metrics from Promethues

### ISSUE THREAD

**Issue by rleungx** [pingcap/pd#2624]
## Development Task
We need PD to give advice for TiDB cloud or TiDB Operator to help decide if we need to scale. So getting metrics from Prometheus is necessary. We can utilize these metrics and some information from store heartbeats and region heartbeats to make a better decision.

**Comment by disksing** [comment]
I think it would be better to use the statistics reported from tikv.

**Comment by rleungx** [comment]
But we still need some statistics of TiDB to help make a decision.

**Comment by disksing** [comment]
I don't think PD should have anything to do with the scale of TiDB instances...

**Comment by nolouch** [comment]
I think AutoScaler strategy API could see as an extended API to suggest how to scale the cluster.
