### ISSUE TITLE
How to run tide cluster on Aliyun/AWS cloud host  ? 

### ISSUE THREAD

**Issue by terryzhao** [pingcap/pd#263]
I'm trying to build a TiDB on Aliyun and AWS using below commands 
./pd-server --cluster-id=1 \
            --name=pd1 \
            --data-dir=pd1 \
            --addr="a.xxx.net:1234" \
            --client-urls="http://a.xxx.net:2379" \
            --peer-urls="http://a.xxx.net:2380" \
            --initial-cluster="colliedb-pd1=http://a.xxx.net:2380,colliedb-pd2=http://b.xxx.net:2380"

The DNS server will resolve the a.xxx.net as public ip address, but AWS/Aliyun doesn't support bind port on public ip address . So i will get the error as below: 

main.go:45: [error] create pd server err listen tcp 54.223.148.78:2380: bind: cannot assign requested address. 

Aliyun/AWS  cloud host has it private ip address , for example 172.2.10.10 .... , but i don't how to use it to bind the port. 

Could you give me any suggestion? 

Thanks!

**Comment by siddontang** [comment]
Maybe you can use like:

```
--client-urls="http://0.0.0.0:2379"
--advertise-client-urls="http://a.xxx.net:2379"
--peer-urls="http://0.0.0.0:2380"
--advertise-peer-urls="http://a.xxx.net:2380"
```

If PD, the client/peer urls is mostly your local listening address, and advertise urls is for outside connection.

**Comment by terryzhao** [comment]
OK, Thanks! I will try it later!
