### ISSUE TITLE
running pd in bash daemon loses etcd logs.

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#265]
In my CentOS test, if I run pd in a script like:

```
pd-server > pd.log 1>&2 &
```

We will lost etcd log, and the etcd log will be found in `/var/log/messsage`, I guess this may be cuased by https://github.com/coreos/pkg/blob/master/capnslog/init.go#L41. 

Maybe we can force redirect etcd log to stderr or file instead.

**Comment by overvenus** [comment]
closed via #269
