### ISSUE TITLE
Consider check the term when update the leader

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#2657]
### Describe your feature request related problem

There are sometimes the PD updates invalid cache information because TiKV reported old heartbeat information, we already consider check the epoch before update the region cache, but the leader changed do not changed the epoch, we need to check the term to prevent the invalid update:

![image](https://user-images.githubusercontent.com/6428910/87640757-c77c3e00-c779-11ea-96f4-1d789924dfb1.png)

### Describe alternatives you've considered

- check the term before updating the region cache to prevent the invalid updates.

### Teachability, Documentation, Adoption, Migration Strategy
- Go
- Relative Code: https://github.com/pingcap/pd/blob/master/server/core/basic_cluster.go#L292-L314

**Comment by nolouch** [comment]
Would you like to try it? @howardlau1999

**Comment by howardlau1999** [comment]
> Would you like to try it? @howardlau1999

Yes, I'll give it a try
