### ISSUE TITLE
use etcd election

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#270]
Now etcd supports assigning session TTL for election, so we can use its election directly.

**Comment by huachaohuang** [comment]
There are some problems with etcd session and election, I fired an issue for etcd https://github.com/coreos/etcd/issues/6681.

I haven't find any workaround so I revert the commit https://github.com/pingcap/pd/commit/4f67c4849ffba295bac9781cb099194ffa8c1714.

I will investigate further after the etcd issue has been resolved.
