### ISSUE TITLE
placement: extract Rule and Batch type out

### ISSUE THREAD

**Issue by xhebox** [pingcap/pd#2701]
### Describe your feature request related problem

While exploring TiDB/ddl goroutine leak test, there is an unnecessary goroutine, which is imported by `server/schedule/placement`. It imported `server/core`, which imported etcd, and finally a function `NewMergerLogger` creating that goroutine. 

Though it is not the root of leak test error, I only want to import the definition of `placement.Rule` or `placement.Batch` from PD. But this makes me feel like I am importing some internal implementations from PD. It is lucky that `func init()` in PD does not mess anything.

### Teachability, Documentation, Adoption, Migration Strategy

Make a subdirectory called `types` or whatever else under `server/schedule/placement`, then fix all references. I can make the PR if there is no objection.

**Comment by disksing** [comment]
It is better to make a copy of the rule definitions.

**Comment by xhebox** [comment]
You mean just define another struct in TiDB? So they are loosely coupled.

**Comment by disksing** [comment]
Yes. Direct source code dependencies could cause many problems. I personally recommend to avoid it as much as possible.

**Comment by xhebox** [comment]
Acceptable. Close it.
