### ISSUE TITLE
support transfer pd leader 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#274]

**Comment by siddontang** [comment]
we may also transfer etcd leader to same pd leader node, of course, this is not mandatory requirement, but an optimization.

/cc @xiang90 I know that now etcd supports transfer leader, but the API seems missing?

**Comment by cppforlife** [comment]
@siddontang would be great to have this feature to promote newly updated machine to be a leader before taking down next node that may be current leader.

**Comment by siddontang** [comment]
Thanks @cppforlife 

We will consider supporting this later, but not in RC2. Maybe you can send us a PR. :-)

**Comment by disksing** [comment]
Fixed by https://github.com/pingcap/pd/pull/702
