### ISSUE TITLE
Server doesn't  return any result without method in curl

### ISSUE THREAD

**Issue by lhy1024** [pingcap/pd#2752]
### What did you do?

To change store state by API

### What did you expect to see?

Change successfully.

### What did you see instead?

The server doesn't return any result 
![image](https://user-images.githubusercontent.com/19542290/89972563-b5b28b80-dc90-11ea-8243-1fdec761f868.png)

it can run in `postman`
![image](https://user-images.githubusercontent.com/19542290/89972806-5903a080-dc91-11ea-9e24-f8a48db92a3e.png)

### What version of PD are you using (`pd-server -V`)?
4.0.2

**Comment by disksing** [comment]
what is the status code?

**Comment by lhy1024** [comment]
> what is the status code?

There is no return value with `curl` and there is `405` in `postman`

**Comment by disksing** [comment]
I think curl has options to display the status code.

**Comment by rleungx** [comment]
You can use `curl -v` to see the status code. e.g.
```
$ curl -v http://127.0.0.1:2379/pd/api/v1/store/1/state\?state\=up
*   Trying 127.0.0.1:2379...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /pd/api/v1/store/1/state?state=up HTTP/1.1
> Host: 127.0.0.1:2379
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< Access-Control-Allow-Origin: *
< Date: Wed, 12 Aug 2020 07:59:51 GMT
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
```
