### ISSUE TITLE
Optimize balancer for large disk

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#285]
Now we use a `MaxDiffScoreFraction` to decide whether to do balance for two stores.
For example, if we want to do capacity balance for store a and b, we calculate

```
a.score = (a.capacity - a.available) / a.capacity
b.score = (b.capacity - b.available) / b.capacity
if a.score - b.score > MaxDiffScoreFraction {
    doBalance(a, b)
}
```

This algorithm cause problem for small data, when `a.score` and `b.score` are smaller than `MaxDiffScoreFraction`, it will never do balance.

For example, if a store has 500G, and `MaxDiffScoreFraction = 0.1`, it will never do balance until the store has used 50G.

But we may fix the problem by calculate the diff score like this

```
if (a.score - b.score) / a.score > MaxDiffScoreFraction {
    doBalance(a, b)
}
```

Also, we need to calculate the post diff score (the estimated diff score after we do balance) to prevent balance back and forth.

```
a.score = (a.capacity - a.available) / a.capacity
b.score = (b.capacity - b.available) / b.capacity
diffScore = (a.score - b.score) / a.score
a.postScore = (a.capacity - a.available - regionSize) / a.capacity
b.postScore = (b.capacity - b.available + regionSize) / b.capacity
postDiffScore = (a.postScore - b.postScore) / a.postScore
if diffScore > MaxDiffScoreFraction && postDiffScore >= 0 {
    doBalance(a, b)
}
```

@qiuyesuifeng

**Comment by siddontang** [comment]
can we construct the test case to verify it?

**Comment by qiuyesuifeng** [comment]
Yes, that is a problem.
But in TiKV, we use compression for data, so `regionSize` maybe not accurate, i am not sure whether it can balance well, we should make some tests.
Another point is that, we use min-capacity-used-ratio(now default value is 0.4, we should update this to a lower value). As you mentioned, if the capacity is too big, this kind of ratio value is not effective, so should we use another value like 10G to make it more flexible by using `min(10G, min-capacity-used-ratio*capacity)`?

**Comment by huachaohuang** [comment]
We can consider the `regionSize` to be smaller than the actual region size.
If we use that `regionSize` to calculate `postScore`, it will be smaller than the actual post score, and we may not do balance, which seems reasonable.
I think the `MinCapacityUsedRatio` and `MaxLeaderCount` will be not necessary any more.

**Comment by qiuyesuifeng** [comment]
How about the test case that one store capacity is very small like 2G, but another one is very big, like 200G, can this method work well?

**Comment by qiuyesuifeng** [comment]
And another point i want to follow is that, how should we prevent the loop balance which is from store A to store B, then next time from store B to A, you should consider this scenario, especially when you have only few regions in store.
