### ISSUE TITLE
How to get key address?

### ISSUE THREAD

**Issue by morefreeze** [pingcap/pd#30]
I think new flow of get key address like this:

0. (optional) ticlient getAllNode including node_id and address.
1. ticlient request pd getRegion(key) and the latter return a region
2. ticlient pick region.peers[0], find corresponding node address(from cache at step 1 or getNode) and send to tikv
3. if peers[0] is leader exactly, then everything is ok. Or go next step
3. if peers[0] is not leader, tikv will return `Not Leader` error and leader info
4. ticlient receive `Not Leader` error, then send the right peer leader

<del>
I want to add a new method `GetKeyAddress` in pd-client. Because ticlient need pass regionID, peer to tikv.

    func (c *Client) GetKeyAddress(k []byte) (region metapb.Region, peer Peer, error) {
        region := c.GetRegion(k)
        peerLeader := raftCluster.getRegionLeader(region.GetRegionID(), region.GetPeers()[0])
        return region, peerLeader, nil
    }
</del>

**Comment by ngaut** [comment]
You may put all of the router information in cache, and always consult the cache first.

**Comment by morefreeze** [comment]
@ngaut Sure, but that's client things, I mean ticlient.

**Comment by siddontang** [comment]
pd client will supply `GetNode` for you, and how to get leader peer is your response, not pd here.

**Comment by morefreeze** [comment]
I agree with you, so update this issue. Please check it to make sure I miss nothing.

**Comment by siddontang** [comment]
Yes, later you can cache nodes, regions and region leaders in client.
