### ISSUE TITLE
bootstrap cluster and generate a cluster id

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#362]
We encounter a few times when we start a TiKV with dirty data and connect to PD, then the whole cluster will be screwed up.

We can let PD bootstrap the cluster and generate a cluster id, then TiKV can use this cluster id to communicate with PD.

For compatibility, cluster id should be an `uint64`, and we may use timestamp for it.

**Comment by siddontang** [comment]
The best way is to use etcd's ClusterID if we can get it. /cc @xiang90

For backward-compatibility, we must provide two ways now. 

1. If user doesn't pass `--cluster-id`, PD generates it. 
2. If user pass `--cluster-id`, PD uses it directly.

Of course, we will set `deprecated` for the `--cluster-id` flag in PD. 
Later, the whole flow is:

1. Bootstrap PD
2. Get PD cluster ID
3. Bootstrap TiKV with this cluster ID.

**Comment by BusyJay** [comment]
I propose appending some random number to timestamp. For example, if timestamp is 1477298735, the cluster id can be 147729873523156.

**Comment by ngaut** [comment]
To keep compatible, We may split 64 into two parts, time and a random number.
We should use UUID in the long term.

**Comment by xiang90** [comment]
@siddontang Cluster ID is attached in any RPC response: https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L328

**Comment by siddontang** [comment]
> Cluster ID is attached in any RPC response

That is great. We can use the etcd's ClusterID directly now. @huachaohuang @overvenus

**Comment by overvenus** [comment]
We can attach a cluster id in the newly added command `GetPDMembers` pingcap/kvproto#108 .

TiKV will validate pd cluster before bootstrapping, also a cluster id will make the validating more reliable.

cc #357 and pingcap/tikv#1201

**Comment by overvenus** [comment]
Any suggestions? @huachaohuang @siddontang @BusyJay

**Comment by huachaohuang** [comment]
Thanks @overvenus , we may need to discuss this issue further, let me handle it.

**Comment by siddontang** [comment]
I think we should add cluster id in every Message. @huachaohuang @overvenus

**Comment by overvenus** [comment]
Attaching a cluster id in every message would be a breaking change.

I think it would be enough that TiKV checks cluster id during establishing a connection.

**Comment by ngaut** [comment]
I agree with @overvenus

**Comment by huachaohuang** [comment]
Isn't cluster id already attached to every message?
https://github.com/pingcap/kvproto/blob/master/proto/pdpb.proto#L224

**Comment by siddontang** [comment]
oh, yes. We have already checked cluster id for every message. I forgot it. 
Seem that GetClusterID API may not check this later.

**Comment by huachaohuang** [comment]
Etcd generates the cluster ID from `initial-cluster-token` and `initial-cluster` configurations, we can generate a random `initial-cluster-token` to get a random cluster ID.

But here's the problem, we don't know the cluster ID until we starts a new PD, which means that we can't start multiple PDs at the same time.
