### ISSUE TITLE
API: support reshuffle leaders

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#383]
Although we have leader balance, we may still meet the condition that some leaders in one TiKV store have more write load.

To reduce the high load for the TiKV, we can reshuffle leaders randomly.

**Comment by siddontang** [comment]
We must also support transfer the leaders to a TiKV as many as possible, then we can support reshuffle.

**Comment by disksing** [comment]
I have concerns that the balance process will be inefficient if we count on random reshuffle.
How about assign a weight to each region base on access statistics, then we balance regions by their weights rather than simply count region numbers?

**Comment by huachaohuang** [comment]
Now we can use API to add a grant-leader-scheduler to transfer leaders to a TiKV, and shuffle-leader-scheduler to shuffle leaders between stores.
