### ISSUE TITLE
Error code should be non-zero when pd start failed

### ISSUE THREAD

**Issue by dengshuan** [pingcap/pd#392]
[Here](https://github.com/pingcap/pd/blob/master/cmd/pd-server/main.go#L61-L64) when server start etcd failed, `return` from main function would exit with error code `0` which actually means command executed successfully.
```
if err != nil {
		log.Errorf("server start etcd failed - %v", errors.Trace(err))
		return
}
```

Besides I saw that signals `SIGHUP, SIGINT, SIGTERM, SIGQUIT` all exit with `0` in pd and tidb code which is a bad practice.

**Comment by overvenus** [comment]
Thank you for your report, it will be fixed soon.

**Comment by huachaohuang** [comment]
What code should we exit with when we get the signals to exit?

**Comment by overvenus** [comment]
@tennix suggests: 130 for `SIGINT`, a non-zero value for `SIGTERM` and `SIGQUIT`. As for `SIGHUP`, it is often used to reload configurations, maybe we should reserve it for future improvements. 

cc @siddontang

**Comment by siddontang** [comment]
The default signal for kill is SIGTERM, which is for graceful shutdown.

**Comment by tennix** [comment]
Yes, `SIGTERM` is usually used to graceful shutdown. Wikipedia has more details about POSIX signals https://en.wikipedia.org/wiki/Unix_signal#POSIX_signals

**Comment by huachaohuang** [comment]
Can we close this now?

**Comment by siddontang** [comment]
For SIGTERM, exit with 0, and for other signal, exit with 1.
