### ISSUE TITLE
Provide more information on PD

### ISSUE THREAD

**Issue by sjmudd** [pingcap/pd#413]
While I understand this project is still young for anyone who would want to consider using TIDB they need to understand how it works and how to configure it. The placement driver carries little behavioural documentation.

I found config.toml which seems to imply that the data is stored 3 times (in 3 different locations), but it's not clear to me at least if that is a redundant distribution or simply that each bit of data may be stored over 3 servers assuming you have enough hardware.

Also it's not clear if a TiKV server goes down and loses data if the cluster will stay fault tolerant. I think that this should be commented on more clearly.
Is it possible to change these settings with a running cluster? It may be I start with a single server with all 3 processes running but then want to use it in a more realistic environment. Ideally I'd like to be able to add more PD, TIKV and TIDB nodes to improve redundancy and / or change the redundancy level but without shutting down the cluster. Is this possible?

If I have failure or want to do maintenance on one of the PD nodes, or one of the TIKV nodes can this be done while the cluster keeps on working? How would do this?

These questions all have an operational feel and I think that the code may be redundant, but I'm not sure if I can change all settings dynamically so clarifying how PD behaves at the moment and how one might manage the cluster when it's up would be most interesting.

**Comment by ngaut** [comment]
Thanks for your valuable suggestions. @sjmudd 
Please add more documents. @siddontang @huachaohuang

**Comment by huachaohuang** [comment]
For now, you can find some documentation about how to add/remove PD or TiKV node [here](https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md#addremove-node-dynamically).

**Comment by huachaohuang** [comment]
For now, you can find some documentation about how to add/remove PD or TiKV node [here](https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md#addremove-node-dynamically).
But yep, sorry about the lack of documentation, we will add more documentation about PD's behavior under different conditions, and the configurations about it.

**Comment by rleungx** [comment]
The issue has been outdated. Close it and feel free to reopen it if you have any questions.
