### ISSUE TITLE
Get stores API support state argument

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#419]
Now the `/pd/api/v1/stores` API list all stores with different states (0,1,2), it will be nice if we can list stores with specified state.
For example, `/pd/api/v1/stores?state=0` list all stores with state = 0.
By default, `/pd/api/v1/stores` can list all stores with state = 0 or state = 1.

**Comment by overvenus** [comment]
I think it would be better using [`"up", "offline" and "tombstone"`](https://github.com/pingcap/kvproto/blob/679b4719adb44bb55780ad2480f29a0f234b039e/pkg/metapb/metapb.pb.go#L42).

**Comment by huachaohuang** [comment]
Yep, it will be better if you can figure out a way to render the store state as "up", "offline" and "tombstone".

**Comment by siddontang** [comment]
Define a type to implement json and toml marshal/unmarshal interface.

**Comment by overvenus** [comment]
Em~, okay, let's keep using 0, 1 and 2 for api consistency and it is much simpler.

@siddontang It is too complex, StoreState is deep nested in [storeInfo](https://github.com/pingcap/pd/blob/c3c9e7e144923bc78242be7fa6772a540052dd47/server/api/store.go#L33).
