### ISSUE TITLE
don't listen and accept connection before PD is ready to serve

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#433]
PD needs some time to initialize before it can serve requests.
The current initialization needs to start etcd first, and once etcd is started, PD will accept connections. Howerver, PD may not ready to serve yet, so it will keep accepting and closing connections until it is ready to serve, which causes a lot of errors and makes user confused.

**Comment by overvenus** [comment]
It seems that the internal etcd starts listening client urls from [`embed.StartEtcd()`](https://github.com/coreos/etcd/blob/cdde0368ad6de945cf262e529cf950c9e0922a49/embed/etcd.go#L80) and we have little control of this.

For now, returning a user-friendly error is the best thing we can do.
