### ISSUE TITLE
support get region by id

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#44]
now we only support get region by key, I think sometimes we may need get region by region id too.
If support, we should add a proto in pdpb.proto, maybe in GetMeta is OK, like 
```
message GetMetaRequest {
    optional MetaType meta_type    = 1;
    optional uint64 node_id        = 2;
    optional uint64 store_id       = 3;
    optional bytes region_key      = 4;
    optional uint64 cluster_id     = 5;
    optional uint64 region_id    = 6;
}
```

If the meta_type is Region and region_key is set, we will use get region, or else region_id is set, we will use get region by id. 

@qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
Agreed, but should we  add a variable like type to show whether get region by id or key?

**Comment by siddontang** [comment]
maybe no need, because they return same value, a region meta.

**Comment by qiuyesuifeng** [comment]
Is it necessary to do this? Seems we have not used it now.
@siddontang

**Comment by qiuyesuifeng** [comment]
No need now, close it.
