### ISSUE TITLE
using another kv server to replace tikv

### ISSUE THREAD

**Issue by finnyyll** [pingcap/pd#443]
Hi, I've developed a kv server and trying to replace TiKV.
The final goal is using my server connect to pd server.

using:  API: pd/api/v1/members
can get the correct result:
```
{
  "members": [
    {
      "name": "pd1",
      "client_urls": [
        "http://10.9.82.25:2379"
      ],
      "peer_urls": [
        "http://10.9.82.25:2380"
      ]
    }
  ]
}
```

but using like : /pd/api/v1/cluster
get the error message :
`"cluster is not bootstrapped"`

Did I missed anything??

**Comment by siddontang** [comment]
Hi @f90005292 

I am confused that why do you want to do this? PD is designed with TiKV. Maybe you can use etcd directly?

**Comment by f90005292** [comment]
Reason is I want to use the ability  of PD(cluster management and the view of the regions)

**Comment by overvenus** [comment]
Hi @finnyyll 

You need to send a bootstrap command. Tikv did this in https://github.com/pingcap/tikv/blob/0833e7f379dfbd05f8a656a00dc5522e1fa4a505/src/server/node.rs#L116.

Here are some extra hints.

 + A rust implementation of PD client. https://github.com/pingcap/tikv/tree/0833e7f379dfbd05f8a656a00dc5522e1fa4a505/src/pd
+ Some related protobuf files. https://github.com/pingcap/kvproto/blob/master/proto/pdpb.proto

**Comment by finnyyll** [comment]
Hi @overvenus 
Thanks for your helpful hints.
