### ISSUE TITLE
Balance region count according to store capacity

### ISSUE THREAD

**Issue by newbcat** [pingcap/pd#444]
The goal of the current storage balance algorithm is to balance storage size between stores, not region count. However, storage size changes very dynamically, but the balance effect takes time to feedback.

For example, if a store has the biggest storage size in the cluster, the balance algorithm will try to remove peer from the store. Unfortunately, the current implementation to remove peer may increase the storage size temporarily, which will cause the balance algorithm keeping removing peer from the store.

If the size of different regions are relative equal, we can try to balance the region count according to store capacity instead. 
For example, we have store 1 with 1GB capacity, store 2 with 2GB capacity, and 6 regions, we can schedule 2 regions to store 1 and 4 regions to store 2. In this way, we will be not affected by the dynamically changing storage size.

**Comment by ngaut** [comment]
We are working on the new algorithm which will balance region count first. Thank you for your advice @newbcat
