### ISSUE TITLE
support disaster recovery

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#451]
In the worst case, we may have little PDs less than the quorum number, e.g, only one PD but had three before. We must supply a way to let user recover the cluster from this disaster. 

Fortunately, etcd has already done this, see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md and https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#disaster-recovery

But we must realize that the new recover cluster has a different cluster ID and metas.

**Comment by andelf** [comment]
Can it be solved by introduce ``--force-new-cluster``?
