### ISSUE TITLE
[question] --join vs --initial-cluster

### ISSUE THREAD

**Issue by cppforlife** [pingcap/pd#466]
it seems that documentation uses `--initial-cluster` flag to start pd nodes and does not make use of `--join` at all. i've also tried restarting each node one by one and it seems it maintains clustered state as each node goes down and comes back. when would one use `--join` instead of `--initial-cluster` as it seems one can just change `--initial-cluster` to add more members?

**Comment by overvenus** [comment]
Hi @cppforlife 

> i've also tried restarting each node one by one and it seems it maintains clustered state as each node goes down and comes back.

This is exactly what we expect, we want a consistent state across all PD servers no matter what happened.

------

`initial-cluster` is used for bootstraping a PD cluster(it contains initial peers of a raft<sup>[1]</sup> cluster). It matters and only matters to **the first run**. Also it can not add peers to a **existing** PD cluster.

However, `join` can add more peers to a **existing** PD cluster. This option should be used with caution, changing cluster members is dangerous!

\[1\]: [raft] is the consensus algorithm used by PD.

[raft]: https://raft.github.io/

**Comment by cppforlife** [comment]
> This is exactly what we expect, we want a consistent state across all PD servers no matter what happened.

that's for the confirmation. 

> However, join can add more peers to a existing PD cluster. This option should be used with caution, changing cluster members is dangerous!

somewhat unfortunate in terms of ease of automation since it means scale up/down is different from spinning up a cluster of desired size. though it's understandable that's it's not a trivial problem to solve.

somewhat related to bootstrapping, if one is starting nodes one at a time (during initial creation or during an upgrade) what's the recommended way to determine the node is healthy and it's ok to continue? checking if port accepts connections of course works; however, are there stronger checks one can make? `http://localhost:2379/pd/api/v1/(version|leader|members)` seem to be pretty useful api endpoints, but it seems that `http://localhost:2379/pd/api/v1/version` (and other endpoints) does not respond when only first node is up.

**Comment by overvenus** [comment]
> however, are there stronger checks one can make? 

Maybe [etcdctl] is the tool you want. PD is based on Etcd, any tools made for etcd should also works fine with PD.

> it seems that `http://localhost:2379/pd/api/v1/version` (and other endpoints) does not respond when only first node is up.

Again, PD is based on Etcd, so any operation that related to etcd would block if we lost majority of a cluster. 

[etcdctl]: https://coreos.com/etcd/docs/latest/admin_guide.html#monitoring

**Comment by cppforlife** [comment]
oh didnt realize that etcd api is exposed at /. i thought it was more of an internal implementation. will look in.
