### ISSUE TITLE
how to update the PD when it joins the cluster with a wrong config. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#477]
Sometimes, we may use a wrong config to join a PD to the cluster. 

E.g, we use a wrong client-url, advertise-client-url, peer-url, advertise-peer-url or name. Or we use a wrong port mapping in docker. 

We may handle above cases differently, can we use the correct the config and restart the PD directly, or must we first remove the PD and then re-join it again?  We should test and add this to FAQ.

**Comment by overvenus** [comment]
For updating client-url, advertise-client-url and name, a simple restart with updated args would be enough.

As for peer-url and advertise-peer-url, we should [update these information](https://coreos.com/etcd/docs/latest/op-guide/runtime-configuration.html#update-a-member) via etcdctl first (removal is unnecessary), then restart it.

More details can be found at [here](https://coreos.com/etcd/docs/latest/op-guide/runtime-configuration.html).

**Comment by siddontang** [comment]
I think we should add this to our FAQ.
