### ISSUE TITLE
support force splitting a region 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#480]
If a region has a very hot read, now we have no way but to increase the coprocessor thread until all all coprocessor threads are 100% CPU.

To fix this, one way is to use follower read, but this is not ready in TiKV. Another way is to force split the region, and then transfer the new region leader to another store.

**Comment by huachaohuang** [comment]
Shouldn't this be implemented in TiKV?

**Comment by siddontang** [comment]
We want to know the whole cluster status through PD and then decide splitting the region manually or through a special scheduler. 

But we still need to think whether doing it is necessary or not.
