### ISSUE TITLE
scheduler should consider different hardware configurations for TiKV

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#489]
Now one user has already used different hardware configurations for TiKV, the machines have different CPU, disk, and memory.

If PD tries to balance the storage and leader evenly, the TiKV in low hardware configuration may become bottleneck. 
Maybe we should add a priority for the TiKV, if the TiKV is in a high configuration, E.g, with more CPU and higher frequency, PD can scheduler more leaders to it. 

/cc @huachaohuang

**Comment by huachaohuang** [comment]
Storage balance has already considered different capacities.
I try to balance leader according to CPU count https://github.com/pingcap/kvproto/pull/138, but as you say, it may cause some problems.

**Comment by siddontang** [comment]
We can add a priority for the TiKV, user can set the priority dynamically through pd-ctl or HTTP API.

**Comment by disksing** [comment]
Fixed by https://github.com/pingcap/pd/pull/713
