### ISSUE TITLE
support a one-shot scheduler 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#491]
Sometimes, we need adding a scheduler to do something like transferring leader for a region, after the operator is finished, we should remove the scheduler to avoid it working but doing nothing forever.  

We can add a one-shot scheduler, after the scheduler generates an operator and the operator is finished, we should remove the scheduler from the coordinator directly. Then we can refactor #483 

We can also add a timeout for the scheduler too.

**Comment by huachaohuang** [comment]
We don't need a scheduler to do this, we can just add operators.

**Comment by siddontang** [comment]
can we add operator dynamically through API now?

**Comment by siddontang** [comment]
or remove the operator
