### ISSUE TITLE
Add a field to indicate a store may be down in store API

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#497]
If a store's down time is longer than `StoreMaxDownTime`, we can add a `is_down` status to the store API.

**Comment by siddontang** [comment]
but for pd-ctl delete, the state 1 is for down too. do we use another concept? like not alive?

**Comment by huachaohuang** [comment]
The state 1 is for offline, state 2 is for tombstone, down is a temporary state.

**Comment by siddontang** [comment]
Got it, so we can use state 3 for down ?

**Comment by huachaohuang** [comment]
Close by #498
