### ISSUE TITLE
pkg/metricutil: bad GetCmdLabel() implementation

### ISSUE THREAD

**Issue by andelf** [pingcap/pd#516]
Bad label string!

GetPDMembers => get_p_d_members

ref:  https://github.com/pingcap/pd/blob/master/pkg/metricutil/metricutil.go#L59

```go
// convertName converts variable name to a linux type name.
// Like `AbcDef -> abc_def`.
func convertName(str string) string {
	name := make([]byte, 0, 64)
	for i := 0; i < len(str); i++ {
		if str[i] >= 'A' && str[i] <= 'Z' {
			if i > 0 {
				name = append(name, '_')
			}
			name = append(name, str[i]+'a'-'A')
		} else {
			name = append(name, str[i])
		}
	}
	return string(name)
}
```

**Comment by andelf** [comment]
I hate CamelCase. :(

**Comment by siddontang** [comment]
Seem that it is not easy to convert GetPDMembers to get_pd_members unless handle the name specially. Do you have any better solution?

**Comment by andelf** [comment]
if there is no single letter words, then:

ABCdeFghiJKLMnOP should be:
ab_cde_fghi_jkl_mn_op

**Comment by siddontang** [comment]
I guess may be the best way is to change the protobuf, rename GetPDMember -> GetPdMember 
/cc @overvenus 

Of course, this can be done with gRPC at same time, so just bear it now. :sob:

**Comment by andelf** [comment]
```ᐅ grep -Rn GetPDMember * | wc -l
      57
ᐅ grep -Rn GetPdMember * | wc -l
      33

**Comment by overvenus** [comment]
Sigh, **PD** is the abbreviation for Placement Driver. I don't think **Pd** is more proper. :confused:
