### ISSUE TITLE
use pkg/errors instead of juju/errors 

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#522]
pkg/errors can record the stack so we can output the error stack directly, no need to use `errors.Wrap` in every error return. 

 + pkg/errors: https://github.com/pkg/errors
 + docs: https://godoc.org/github.com/pkg/errors

/cc @disksing @overvenus

**Comment by overvenus** [comment]
Well, I am OK with it.

BTW, pkg/errors only traces top 32 stacks.
https://github.com/pkg/errors/blob/a887431f7f6ef7687b556dbf718d9f351d4858a0/stack.go#L124

**Comment by siddontang** [comment]
I think 32 stacks is enough.
