### ISSUE TITLE
Store id numbering is weird

### ISSUE THREAD

**Issue by andelf** [pingcap/pd#525]
Now TiDB cluster automatically assign store ids.

If I start many tikvs at once, these ids may be:

    1 4 7 8 ...

If I add a tikv after one or two days running, the new store id may be a very large number, for e.g. 

    3647593

The numbering scheme is weird. 😢

**Comment by siddontang** [comment]
All store, region and peer use the same ID generator, so it is not strange with a larger ID for store. And we can't use different generator for different types because of the compatibility, so maybe it won't be fixed now.
