### ISSUE TITLE
Consider saving configs to etcd.

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#544]
Now pd-server supports setting up configs at runtime using pd-ctl. But the configuration changes are only applied to current leader. After leader changes, the default configuration will take effect again.

We may consider saving configs to etcd, or do you guys have any other suggestions?

/cc @siddontang @andelf @nolouch

**Comment by siddontang** [comment]
Duplicated with #258 

IMO, we should save the scheduler config in etcd.
