### ISSUE TITLE
PD-Client:make sure each new tso from pd is bigger than old one

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/pd#578]
This issue is used to make sure each new `ts` get from `pd-server` is bigger than old one. It's also related to make sure `start_ts` is always  smaller than `commit_ts` in transaction  ([tikv/issue_1688]([tikv/issue_1688](https://github.com/pingcap/tikv/issues/1688)). 

This issue should be fixed after GRPC.

**Comment by siddontang** [comment]
@AndreMouche 

How can PD guarantee this?

**Comment by AndreMouche** [comment]
We can not guarantee this in `pd-server` while `pd-client` do.  Since PD client use a single connection, send quest in batch, it can make sure TS is greater than last TS. @siddontang
