### ISSUE TITLE
consider first transefer leader when store offline

### ISSUE THREAD

**Issue by nolouch** [pingcap/pd#636]
currently, we transfer peer directly when the store offline. we can transfer leader firstly then remove this peer. and we should make sure the operator does not time out.

**Comment by siddontang** [comment]
can we close it now? @nolouch

**Comment by disksing** [comment]
I've checked the code. Now whenever create a removePeer operator, it will transfer leadership first if the peer is leader. See: https://github.com/pingcap/pd/blob/38eb8a2e70dd39668a62d24a79f30596f204df14/server/scheduler.go#L278
https://github.com/pingcap/pd/blob/38eb8a2e70dd39668a62d24a79f30596f204df14/server/scheduler.go#L266
I think we can close the issue. @nolouch

**Comment by nolouch** [comment]
yep, we can close it
