### ISSUE TITLE
Leap second problem

### ISSUE THREAD

**Issue by biolee** [pingcap/pd#680]
How pd deal with leap second while doing transaction

as far as I can see, when write happen in the "second leap second" (eg "11:59:59.005"), one will read a old value that written in the "first leap second" (eg "11:59:59.888") 

ps: 
- https://github.com/golang/proposal/blob/master/design/12914-monotonic.md
- https://blog.golang.org/toward-go2

**Comment by siddontang** [comment]
Hi @biolee 
PD can detect it. If the time jumps back, PD will not allocate the TSO for the transaction until the time is newer than the last saved correct TSO time.

**Comment by choleraehyq** [comment]
@siddontang 
There might be some problem about this after we upgrade to go 1.9.
In go 1.9, `time.Sub` will use monotonic clock. So `t2.Sub(t1)` might be a positive time, with `t2.UnixNano()` smaller than `t1.UnixNano()`.
Consider this demo program:
```
package main

import (
    "fmt"
    "time"
)

func main() {
    t1 := time.Now()
    time.Sleep(10 * time.Second)
    t2 := time.Now()
    fmt.Println(t2.Sub(t1))
    fmt.Println(t1)
    fmt.Println(t1.UnixNano())
    fmt.Println(t2)
    fmt.Println(t2.UnixNano())
}
```

I run it and reset my wall clock during `time.Sleep(10 * time.Second)`, and it prints:

```
10.000186317s
2017-07-14 10:17:04.365994758 +0800 CST m=+0.000251610
1499998624365994758
2017-07-14 10:00:07.531633247 +0800 CST m=+10.000437927
1499997607531633247
```

Does this behaviour have any bad affection to PD?

**Comment by choleraehyq** [comment]
As a comparision, in go 1.8.3, the above program will print:
```
-28m45.291337634s
2017-07-14 10:28:52.443618511 +0800 CST
1499999332443618511
2017-07-14 10:00:07.152280877 +0800 CST
1499997607152280877
```

**Comment by disksing** [comment]
Thanks for reminding! @biolee @choleraehyq 
I think we truly have a problem here. I'll get it fix soon.

**Comment by choleraehyq** [comment]
Fixed in https://github.com/pingcap/pd/pull/681.
