### ISSUE TITLE
can not remove pd node with no name

### ISSUE THREAD

**Issue by yitu-z** [pingcap/pd#694]
such case as follow:
member
{
  "members": [
    {
      "name": "pd1",
      "member_id": 2754188069649431448,
      "peer_urls": [
        "http://10.30.96.29:2380"
      ],
      "client_urls": [
        "http://10.30.96.29:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 4706578448982392122,
      "peer_urls": [
        "http://10.30.96.13:2380"
      ],
      "client_urls": [
        "http://10.30.96.13:2379"
      ]
    },
    {
      "member_id": 5209400361606882645,
      "peer_urls": [
        "http://10.135.216.15:2380"
      ]
    },
    {
      "name": "pd3",
      "member_id": 13334041265382149877,
      "peer_urls": [
        "http://10.30.96.21:2380"
      ],
      "client_urls": [
        "http://10.30.96.21:2379"
      ]
    }
  ]
}

**Comment by yitu-z** [comment]
/home/tidb/pd/bin/pd-ctl -u http://10.135.216.15:2379
» member
{
  "members": [
    {
      "name": "pd-1a",
      "member_id": 16935746038455529069,
      "peer_urls": [
        "http://10.135.216.15:2380"
      ],
      "client_urls": [
        "http://10.135.216.15:2379"
      ]
    }
  ]
}

**Comment by yitu-z** [comment]
pd1/2/3 are always report rafthttp ignore as follow:
 [error] rafthttp: [request sent was ignored (cluster ID mismatch: remote[484b82073e5ea555]=4752153d484af579, local=6850722f39c4f3df)]
^C

**Comment by yitu-z** [comment]
[error] rafthttp: [request cluster ID mismatch (got 6850722f39c4f3df want 4752153d484af579)]
^C

**Comment by disksing** [comment]
Hi @yitu-z , could you let me know how do you start the pd cluster?

**Comment by yitu-z** [comment]
width the start_pd.sh generated by ansible,and add  the  --join parameter. 
#!/bin/bash
set -e
ulimit -n 1000000

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
DEPLOY_DIR=/home/tidb/deploy

cd "${DEPLOY_DIR}" || exit 1

exec bin/pd-server \
    --name="pd-1a" \
    --client-urls="http://10.135.216.15:2379" \
    --advertise-client-urls="http://10.135.216.15:2379" \
    --peer-urls="http://10.135.216.15:2380" \
    --advertise-peer-urls="http://10.135.216.15:2380" \
    --data-dir="/home/tidb/deploy/data.pd" \
    --join="http://10.30.96.29:2379" \
    --config=conf/pd.toml \
    -L "info" \
    --log-file="/home/tidb/deploy/log/pd.log" \

**Comment by disksing** [comment]
Just to make sure if I'm understanding correctly. Do you first starts a 3-nodes pd cluster, consisting of pd1, pd2, pd3, then you want to add another pd 'pd-1a' using join?

**Comment by yitu-z** [comment]
the situation is there are 4 node in pd cluster and one is no name now.how to  remove the node with no name?

**Comment by yitu-z** [comment]
it seems the pd-1a node only sees itself

**Comment by yitu-z** [comment]
the only problem is how to remove the incorrect pd node and rejoin it again

**Comment by disksing** [comment]
@yitu-z 
Unfortunately, pd-server now does not support removing a member with no name. I'll add a new API soon after.
Now I'm more curious about why the new pd created a new cluster with the `join` argument. Maybe you have accidentally started it without the `join` argument once?

**Comment by yitu-z** [comment]
the other problem is how to change the  pd-1a's cluster ID from 6850722f39c4f3df to 4752153d484af579

**Comment by yitu-z** [comment]
and how to add name to the pd-1a node in the cluster manually.

**Comment by disksing** [comment]
I suspect there are  something wrong in the process of starting new pd. May I have your pd-1a's log?

**Comment by yitu-z** [comment]
lukgem.com/pd.log.tar.gz

**Comment by yitu-z** [comment]
[pd.log.tar.gz](https://github.com/pingcap/pd/files/1192880/pd.log.tar.gz)

**Comment by yitu-z** [comment]
great！

**Comment by disksing** [comment]
Hi, as far as I can tell from you log, when you start the new pd for the first time, there seems be some old data in `data-dir`. I suggest you clear all data of the new pd, then starts pd with join again. The remaining unnamed pd can be removed using the new API later.

**Comment by yitu-z** [comment]
ok,thanks .

**Comment by disksing** [comment]
Hi @yitu-z ,
Now with the latest master, you can remove a peer by its id. You may use pd-ctl `member delete id {id}` or the HTTP api `curl -X DELETE http://pd-addr:2379/pd/api/v1/members/id/{id}`.
If any problems come out, please fell free to feedback.

**Comment by yitu-z** [comment]
member delete
delete a member

Usage:
  delete [command]

Available Commands:
  id          delete a member by id
  name        delete a member by name

Use "help delete [command] " for more information about a command.
» member delete id 5209400361606882645
Failed to delete member 5209400361606882645: [404] 404 page not found

» member delete id 5209400361606882645
Failed to delete member 5209400361606882645: [404] 404 page not found

**Comment by yitu-z** [comment]
$bin/pd-ctl -u http://10.30.96.29:2379
» member
{
  "members": [
    {
      "name": "pd1",
      "member_id": 2754188069649431448,
      "peer_urls": [
        "http://10.30.96.29:2380"
      ],
      "client_urls": [
        "http://10.30.96.29:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 4706578448982392122,
      "peer_urls": [
        "http://10.30.96.13:2380"
      ],
      "client_urls": [
        "http://10.30.96.13:2379"
      ]
    },
    {
      "member_id": 5209400361606882645,
      "peer_urls": [
        "http://10.135.216.15:2380"
      ]
    },
    {
      "name": "pd3",
      "member_id": 13334041265382149877,
      "peer_urls": [
        "http://10.30.96.21:2380"
      ],
      "client_urls": [
        "http://10.30.96.21:2379"
      ]
    }
  ]
}
