### ISSUE TITLE
404 page not found when delete pd member by id

### ISSUE THREAD

**Issue by yitu-z** [pingcap/pd#732]
$bin/pd-ctl -u http://10.30.96.29:2379
» member
{
  "members": [
    {
      "name": "pd1",
      "member_id": 2754188069649431448,
      "peer_urls": [
        "http://10.30.96.29:2380"
      ],
      "client_urls": [
        "http://10.30.96.29:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 4706578448982392122,
      "peer_urls": [
        "http://10.30.96.13:2380"
      ],
      "client_urls": [
        "http://10.30.96.13:2379"
      ]
    },
    {
      "member_id": 5209400361606882645,
      "peer_urls": [
        "http://10.135.216.15:2380"
      ]
    },
    {
      "name": "pd3",
      "member_id": 13334041265382149877,
      "peer_urls": [
        "http://10.30.96.21:2380"
      ],
      "client_urls": [
        "http://10.30.96.21:2379"
      ]
    }
  ]
}

» member delete
delete a member

Usage:
  delete [command]

Available Commands:
  id          delete a member by id
  name        delete a member by name

Use "help delete [command] " for more information about a command.
» member delete id 5209400361606882645
Failed to delete member 5209400361606882645: [404] 404 page not found

» member delete id 5209400361606882645
Failed to delete member 5209400361606882645: [404] 404 page not found

**Comment by disksing** [comment]
Hi @yitu-z , may I have your pd-server's version? (`./pd-server -V`)

**Comment by yitu-z** [comment]
$./pd-server -V
Git Commit Hash: c05ef8174934a0364cd86b1c16cfa523e52d6301
UTC Build Time:  2017-07-20 02:31:17

**Comment by disksing** [comment]
The server is too old and not support this feature. You need to upgrade pd-server to a version later than RC4(30115ae539e7e175e988b8c70b630f0908d7a77b).

**Comment by yitu-z** [comment]
rolling update failed,see https://github.com/pingcap/tidb/issues/4442

**Comment by disksing** [comment]
Not related to pd. Closing.
