### ISSUE TITLE
create schedulers base on configuration.

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#738]
Now schedulers are initially created statically: https://github.com/pingcap/pd/blob/5cb02b14cd67457f3328c773cfee969241790869/server/coordinator.go#L128-L134

We can also add/remove schedulers at runtime:
https://github.com/pingcap/pd/blob/7b9052c149bab4febdf685aaa1b64ca4680b4303/server/handler.go#L71
https://github.com/pingcap/pd/blob/7b9052c149bab4febdf685aaa1b64ca4680b4303/server/handler.go#L80

We need to do:
1. make it configurable, support load initial schedulers' names from config file.
2. after add/remove a scheduler, the schedulers list should persist to etcd. So the schedulers can be recreate after leader change or pd-server restart.

**Comment by Connor1996** [comment]
#759 #769

**Comment by Connor1996** [comment]
#769
