### ISSUE TITLE
add mockCluster to test schedulers.

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#752]
It should have methods that the [schedule.Cluster](https://github.com/pingcap/pd/blob/63a7cdf6a86252f4f3cd3c1e44939ac185640f7c/server/schedule/scheduler.go#L25) interface describes and methods we need for testing(see methods of [testClusterInfo](https://github.com/pingcap/pd/blob/63a7cdf6a86252f4f3cd3c1e44939ac185640f7c/server/balancer_test.go#L31)).
Then we can move tests in `server/balancer_test.go` into `server/schedulers` directory.

**Comment by qqsun8819** [comment]
OK, I'll take this

**Comment by disksing** [comment]
Fixed.
