### ISSUE TITLE
can etcd Election speed up leader failover

### ISSUE THREAD

**Issue by siddontang** [pingcap/pd#76]
https://github.com/coreos/etcd/blob/master/clientv3/concurrency/election.go

**Comment by siddontang** [comment]
I see etcd Election use session timeout https://github.com/coreos/etcd/blob/master/clientv3/concurrency/election.go#L53, so it will wait at lease 60s to re-elect again if current leader was down, this is too long for us.

Maybe we should think another way to speed up it, and the client must handle this scenario carefully too.

**Comment by qiuyesuifeng** [comment]
We use watch for leader failover on etcd, it costs about five seconds to handle it, so i think it is OK now.
@siddontang  What is your opinion? Can this issue be closed?

**Comment by siddontang** [comment]
@xiang90 told me before that he would try to speed up in test, does it support now? If not, we can close it.
