### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by vaibhavsood** [pingcap/pd#783]
Hi, 

Wanted to check if there are plans to make the docker images on dockerhub official? The steps for doing that are as per here: https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

I found the docker hub image here https://hub.docker.com/r/pingcap/pd/ but this does not come under docker's official image list

**Comment by shenli** [comment]
@vaibhavsood Thanks for your advice! We will take a look.

**Comment by tennix** [comment]
@vaibhavsood Thanks for your advice, but we don't plan to make these images to dockerhub official images. `pd` may have other meanings if not under `pingcap`. Besides our release schedule may be different from dockerhub official images

**Comment by disksing** [comment]
Closing for now. Please feel free to reopen if you have any further information.
