### ISSUE TITLE
when pd “join” to a pd cluster，if  “--log-file“ directory is the same as data-dir,It will be failed 

### ISSUE THREAD

**Issue by wupaopao** [pingcap/pd#819]
It will be failed when pd using the way “join” to join a pd cluster and the “ --log-file“ dir being the same as “data-dir”.
Reason:
The code judge a pd for a failed pd or a deleted pd only by if the “data-dir” is empty When excuting "server.PrepareJoinCluster" in main.go. If "data-dir" has any file,the judging will be wrong.

Chinese(中文版):
当pd用“join”方式加入pd cluster时，假如指定“--log-file”的目录和“data-dir”一样时，则加入集群失败。
原因是在执行main.go中的server.PrepareJoinCluster时，判断一个pd 为 failed PD 或deleted PD时，仅仅判断data-dir是否为空，当该dir有任意文件时，都会导致加入失败。

**Comment by nolouch** [comment]
thanks! @wupaopao 
maybe you can help us to fix it. 
BTW, would you please change the Chinese comment to English?

**Comment by siddontang** [comment]
I think we should forbid using the same directory for log and data. 

@wupaopao @nolouch

**Comment by wupaopao** [comment]
@siddontang I think the existing way to judge a pd old or not is too simple.Maybe we should find a featured file to determine whether the pd is old or not.

**Comment by siddontang** [comment]
@wupaopao 

The file can still be removed accidentally. So we may still have no way to check this.

**Comment by disksing** [comment]
Closing for now. Please feel free to reopen if you have any further information.
