### ISSUE TITLE
Question: In PD cluster, whether the PD Leader will be the receiver for TiKV region/store heartbeat

### ISSUE THREAD

**Issue by yeyuqiang** [pingcap/pd#873]
After a quick look at PD source code, a question come to my mind.
In server/leader.go#leaderLoop, it seems that only one PD will be the leader, others will watch it util the PD Leader fail or be resigned, Does it means that no matter how PD instance I have started in the PD Cluster, the really working PD is only the leader? When TiKV send region/store heartbeat , does the PD Leader will be the only receiver? 
If so, will the PD be performance bottleneck when TiKV cluster being enlarged and data grows up explosively?

**Comment by disksing** [comment]
Hi @yeyuqiang , thanks for your feedback.

> When TiKV send region/store heartbeat , does the PD Leader will be the only receiver?

Yes. You may think other pd-servers are for disaster preparedness.

> Will the PD be performance bottleneck when TiKV cluster being enlarged and data grows up explosively?

Yes. It could overload if there are too many regions. In our test environment, pd-server can smoothly handle heartbeats for about 500k regions.
If you observe the pd-server's CPU load is too high in a large cluster, you may consider adjusting tikv's [region heartbeat config](https://github.com/pingcap/tikv/blob/ecf816096a54226ae0ddafd500b4b5d1d760d87b/etc/config-template.toml#L100) to a longer interval.

**Comment by yeyuqiang** [comment]
thanks for your reply.
