### ISSUE TITLE
Can pd provide unnormal tikv region statistics and other unexpect status for monitor

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/pd#924]
Schrodinger should know if some test  impact tikv and others. so we need monitor region statistics for tikv region and other unexpect status

**Comment by siddontang** [comment]
If PD finds a region doesn't have the leader for a long time, it can raise an alert or we can know this from PD API.

**Comment by zhouqiang-cl** [comment]
And if schrodinger can obtain all status for tikv/tidb from pd？schrodinger need to make sure if tidb/tikv is health too

**Comment by disksing** [comment]
Thanks for you advise @zhouqiang-cl. We will need to add some API(s) to query the health statistics.
Could you help to make a list of the unexpected status you may want to know?
Presumably, I think it may need to include the count of regions that:
- misses heartbeat
- lacks of replica
- has extra replicas
- needs to move to a store with better label
- locates on the wrong namespace

**Comment by zhouqiang-cl** [comment]
hi, I think you can return the status of such as region error with detail info or kv error(kv die/hang ...)   @disksing .I don't have a list of unexpected status, beacuse I want to get all info from pd ~~o(>_<)o ~~

**Comment by GregoryIan** [comment]
I think we can only provide a unified standard for discussion, like below.  
How to classify and define every level, more experience and discussion,
- level
   -  critical/blow
   -  error/red
   -  unhealthy/yellow
   -  healthy/green
- description
- instruction
