### ISSUE TITLE
if store lost heartbeat, how pd to handle this situation

### ISSUE THREAD

**Issue by shilicqupt** [pingcap/pd#926]
I have such confusion, StoreHeartbeat only record store statistics, if store lost heartbeat, how pd to handle this, any alarm send ?

**Comment by disksing** [comment]
In short, PD sets different states for store based on the duration of its heartbeat, which can be queried through the HTTP API (/pd/api/v1/stores).

If your tidb cluster has the prometheus and grafana components installed, you can also observe the current states of stores in the PD Panel:
![2018-01-18 18-06-24](https://user-images.githubusercontent.com/12077877/35093331-1b3ec35c-fc7d-11e7-83f8-6cf9ec33595a.png)

However, we do not think PD should be responsible for sending alarms, which is better to be the responsibility of an external monitoring system. Of course, you can customize your monitoring system by using PD API or grafana data.

**Comment by shilicqupt** [comment]
got it
