### ISSUE TITLE
Reduce empty region's replica count to 1

### ISSUE THREAD

**Issue by BusyJay** [pingcap/pd#952]
Before merge is stable enough, if we want to handle the situation that there are many empty regions, we can change their replica count to 1. So for empty regions, there will be no election, no heartbeat and no message append, the impact of them can be minimized. Pd may still suffer from too many regions though.

**Comment by ngaut** [comment]
We can't do that. The region is empty for now does not mean it's always empty, someone may write to the empty region.

**Comment by BusyJay** [comment]
It's not a general approach. But for the cases that we know for sure that the region will not be written again, it's still a temporary way to ease the problem.

**Comment by disksing** [comment]
Now we have region merge. Don't need it.
