### ISSUE TITLE
offline store need be considered in balance leader/region

### ISSUE THREAD

**Issue by disksing** [pingcap/pd#974]
When a store is not up, it is excluded from the leader/region balance. I think a better behavior  would be:
1. If the count(or size) of an offline store is below average, we can exclude it in balancers.
2. If the count(or size) of an offline store is above average, we should consider it in balancers.

**Comment by huachaohuang** [comment]
I think we can limit an offline store as a source store (but not a target store) in balancers.

**Comment by nolouch** [comment]
Maybe we can consider a new single fail-over balance, now checker couldn't found abnormal region immediately. and there are some priorities for scheduling the fail store regions. like hot region.

**Comment by disksing** [comment]
Yes we can. But I guess it's not related to this issue.
